force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Plots</fullName>
            </value>
            <value>
                <fullName>Villas &amp; Plots</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>As on stage</fullName>
                <isActive>false</isActive>
                <label>As on stage</label>
            </value>
            <value>
                <fullName>Custom</fullName>
                <isActive>false</isActive>
                <label>Custom</label>
            </value>
            <value>
                <fullName>Differed</fullName>
                <isActive>false</isActive>
                <label>Differed</label>
            </value>
            <value>
                <fullName>Full Payment</fullName>
                <isActive>false</isActive>
                <label>Full Payment</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Plot_Type__c.field-meta.xml
<CustomField>
    <fullName>Plot_Type__c</fullName>
    <label>Plot Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nirvana</fullName>
            </value>
            <value>
                <fullName>Zion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Plots</fullName>
            </value>
            <value>
                <fullName>Villas &amp; Plots</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_status__c.field-meta.xml
<CustomField>
    <fullName>Quote_status__c</fullName>
    <label>Quote status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drafted</fullName>
                <default>true</default>
                <label>Drafted</label>
            </value>
            <value>
                <fullName>submitted for approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>sent to customer</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/quotePdfController.cls
public class quotePdfController {
    @auraEnabled
    public static string getPaymentType(string recId){
        List<Quote__c> qt = [SELECT Id,Property_Type__c FROM Quote__c WHERE Id =:recId LIMIT 1];
        string returnprotype;
        if(qt[0].Property_Type__c !=null){
            returnprotype= qt[0].Property_Type__c;
        }
        return returnprotype;
    }
    @AuraEnabled
    public static string sendEmailtoCustomer(String recId)
    {
        Quote__c qt = [SELECT Id,Quote_status__c,Property_Type__c,payment_type__c,Approval_status__c, Project__c, SLead__r.Email__c, SLead__r.Secondary_Email__c,Plot_Type__c   FROM Quote__c WHERE Id=:recId];
        if(qt.Quote_status__c == 'Approved' || qt.Quote_status__c == 'sent to customer'){
            Messaging.SingleEmailMessage semail = new Messaging.SingleEmailMessage();
            Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
            PageReference pref;
            
            if(qt.Property_Type__c=='Apartment'){
                pref= page.AppartmentCostSheet;
                
            }else{
                pref= page.VillaCostSheet;
            }
            
            
            pref.getParameters().put('id',recId);
            pref.setRedirect(true);
            system.debug(pref);
            Blob b;
            if(Test.isRunningTest()){
                b = blob.valueOf('Unit.Test');
            }else{
                b = pref.getContent();
            }
            attach.setFileName('SOWPARNIKA_Quotation.pdf');
            attach.setBody(b);
            semail.setSubject('SOWPARNIKA Quotation');
            
            List<string> sendTo = new List<string>();
            if(qt.SLead__r.Email__c !=null){
                sendTo.add(qt.SLead__r.Email__c);
            }
            
            if(qt.SLead__r.Secondary_Email__c !=null){
                sendTo.add(qt.SLead__r.Secondary_Email__c);
            }
            
            semail.setToAddresses(sendTo);
            semail.setHtmlBody('Dear Sir/Madam,<br/> <br/> Thank you very much for your interest in '+qt.Project__c +'.<br/>Please find the attached quote for your kind Perusal.<br/>Note: This is a sample quote purely for reference.<br/>Please feel free to talk us for clarification if any.,<br/>');
            semail.setFileAttachments(new Messaging.EmailFileAttachment[]{attach});
            if(sendTo.size()>0){
                Messaging.sendEmail(new Messaging.SingleEmailMessage[]{semail});
                system.debug(semail);
                
                Quote__c q = [select Id, Name, Quote_status__c from Quote__c where id = :recId limit 1];
                q.Quote_status__c = 'sent to customer';
                update q;
                return 'Quotation sent to customer';
            }else{
                return 'Please enter email address in lead';
            }
        }else{
            return 'Quote is not approved, you can not send Quote';
        }
    }
    
    
}