force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SiteVisit-{0000}</displayFormat>
        <label>Site Visits Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Scheduled Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendSMSTest.cls
@isTest
public class SendSMSTest {
    @isTest
    public static void testSendSMS() {
        List<Site_Visit__c> svList = new List<Site_Visit__c>();
        List<Lead> leadList = new List<Lead>();

        for(Integer i = 0; i < 5; i++) {
            Lead ld = new Lead(
                LastName = 'Test Lead ' + i,
                Phone__c = '123456789' + i,
                Lead_Source__c = 'Website',
                OwnerId = UserInfo.getUserId(),
                Primary_Source_OTP__c = '123' + i,
                Allocated_project__c = 'Test Project'
            );
            insert ld;
            leadList.add(ld);
        }

        for(Lead ld : leadList) {
            Site_Visit__c sv = new Site_Visit__c(
                Date__c = Datetime.now().addDays(1),
                SLead__c = ld.Id,
                Project__c = 'Test Project',
                OwnerId = UserInfo.getUserId()
            );
            svList.add(sv);
        }
        insert svList;
        Test.startTest();
        sendSVOTP.sendSMS(svList);
        Test.stopTest();

    }
}