force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <displayFormat>SCP-{0000}</displayFormat>
        <label>Channel Partner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ChannelPartnerRegistrationTest.cls
@isTest
public class ChannelPartnerRegistrationTest {
    @isTest
    public static void testDoPost_Products() {
        Channel_Partner__c cp = new Channel_Partner__c();
        cp.Name__c = 'test';
        cp.Active__c = true;
        
        String requestData = '';
        
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestURI = '/services/apexrest/CPR/CPName';
        request.requestBody = Blob.valueOf(requestData);
        request.httpMethod = 'GET';
        RestContext.request = request;
        RestContext.response = response;
        ChannelPartnerRegistration.getChannelPartners();
        
        
        RestRequest request1 = new RestRequest();
        RestResponse response1 = new RestResponse();
        request.requestURI = '/services/apexrest/CPR/CPNam';
        request.requestBody = Blob.valueOf(requestData);
        request.httpMethod = 'GET';
        RestContext.request = request1;
        RestContext.response = response1;
        ChannelPartnerRegistration.getChannelPartners();
    }
    
    @isTest
    public static void testDoPost_Invoices() {
        String requestData = '{"cptype":"Individual","Name":"cp1234","emailId":"cp@123.com","mobileNumber":"8876678890","reraRegistration":"Yes","reraNumber":"INV001","gstRegistration":"Yes","gstNumber":"1123343454","ownerDetails":"giri1232","workAddress":"rrrrrttyttt","teamSize":"12"}';
     Channel_Partner__c cp = new Channel_Partner__c();
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestURI ='/services/apexrest/CPR/CP'; 
        request.requestBody = Blob.valueOf(requestData);
        request.httpMethod = 'POST';
        RestContext.request = request;
        RestContext.response = response;
        ChannelPartnerRegistration.captureLead();
        
        RestRequest request1 = new RestRequest();
        RestResponse response1 = new RestResponse();
        request.requestURI ='/services/apexrest/CPR/CP1'; 
        request.requestBody = Blob.valueOf(requestData);
        request.httpMethod = 'POST';
        RestContext.request = request1;
        RestContext.response = response1;
        ChannelPartnerRegistration.captureLead();
}


}