force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <displayFormat>SCP-{0000}</displayFormat>
        <label>Channel Partner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ChannelPartnerRegistrationEmailTest.cls
@isTest
public class ChannelPartnerRegistrationEmailTest {
    @isTest
    public static void testClass(){
        Channel_Partner__c cp = new Channel_Partner__c();
        cp.Name__c = 'test1234';
        cp.Email_Id__c = 'arun@fingertipplus.com';
        cp.Approval_Status__c = 'Approved';
        insert cp;
        
        List<Id> lstCp = new List<Id>();
        lstCp.add(cp.id);
        ChannelPartnerRegistrationEmail.sendEmail(lstCp);
    }

}