force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <displayFormat>SCP-{0000}</displayFormat>
        <label>Channel Partner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/getSalesUsersTest.cls
@isTest
public class getSalesUsersTest {
    @isTest
    public static void testDoPost_Products() {
        Channel_Partner__c cp = new Channel_Partner__c();
        cp.Name__c = 'test';
        cp.Active__c = true;
        
        String requestData = '';
        
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestURI = '/services/apexrest/SAL/Sales';
        request.requestBody = Blob.valueOf(requestData);
        request.httpMethod = 'GET';
        RestContext.request = request;
        RestContext.response = response;
        getSalesUsers.getSalesUsersss();

    }

}