force-app/main/default/objects/Apex_Log__c/Apex_Log__c.object-meta.xml
<CustomObject>
    <label>Apex Log</label>
    <nameField>
        <displayFormat>APEX-{0000}</displayFormat>
        <label>Apex Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Log__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/getCampaignNames.cls
@RestResource(urlMapping='/CAM/*')
global without sharing class getCampaignNames {
     @HttpGet
    global static void getCamps(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        Apex_Log__c log = new Apex_Log__c();
        log.Request_Type__c ='HttpGet Campaign';
        List<String> cpNames = new List<String>();
        try{
            String databox = req.requestBody.toString();
            String objectName = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
            log.Request_Type__c ='HttpGet Campaign'+objectName;
            log.Request__c = databox;
            if (objectName == 'Campaign') {
                List<Campaign> cpList = [SELECT id, Name FROM Campaign WHERE IsActive = true];
                for(Campaign cp : cpList){
                    cpNames.add(cp.Name);
                }
                String jsonResponse = JSON.serialize(cpNames);
                res.addHeader('Content-Type', 'application/json');
                res.responseBody = Blob.valueOf(jsonResponse);
                res.statusCode = 200; // Set success status code
                log.Response__c = jsonResponse;
                log.Status__c = 'Success';
                return;
            }
        }
        catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            res.statusCode = 500;
            res.responseBody = Blob.valueOf('Internal Server Error');
            log.status__c='FAILED';
            log.Error_Message__c = e.getMessage();
        }
        
        insert log;
        
    }

}