force-app/main/default/objects/Apex_Log__c/Apex_Log__c.object-meta.xml
<CustomObject>
    <label>Apex Log</label>
    <nameField>
        <displayFormat>APEX-{0000}</displayFormat>
        <label>Apex Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Source__c/Related_Source__c.object-meta.xml
<CustomObject>
    <label>Enquiry Source</label>
    <nameField>
        <displayFormat>RS-{000}</displayFormat>
        <label>Enquiry Source</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiry Sources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Source__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Enquiry Sources</relationshipLabel>
    <relationshipName>Enquiry_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Source__c/fields/Source_OTP__c.field-meta.xml
<CustomField>
    <fullName>Source_OTP__c</fullName>
    <label>Source OTP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OTPBatchClassRS.cls
public class OTPBatchClassRS implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable{
    private Set<Id> leadRecords;
    private Integer batchSize;
    private String otpType;
    
    public OTPBatchClassRS(Set<Id> leads, Integer batchSize, String otpType) {
        this.leadRecords = leads;
        this.batchSize = batchSize;
        this.otpType = otpType;
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Id,Name, Source_OTP__c, Lead__r.Phone__c,Lead__r.LastName,Lead__r.Allocated_project__c FROM Related_Source__c WHERE Id IN :leadRecords]);
    }
    
    public void execute(Database.BatchableContext BC, List<Related_Source__c> scope) {
        List<Apex_Log__c> logs = new List<Apex_Log__c>();
        for (Related_Source__c ld : scope) {
            Apex_Log__c log = sendOTPMube.sendOTP(ld.Source_OTP__c, ld.Lead__r.Phone__c, ld.Lead__r.LastName, 'LeadEnquiry', ld.Lead__r.Allocated_project__c); 
            logs.add(log);
        }
        if (!logs.isEmpty()) {
            insert logs;
        }
    }
    
    public void finish(Database.BatchableContext BC) {
    }
    
    public void execute(SchedulableContext sc) {
        Database.executeBatch(this, batchSize);
    }
    
}