force-app/main/default/objects/Apex_Log__c/Apex_Log__c.object-meta.xml
<CustomObject>
    <label>Apex Log</label>
    <nameField>
        <displayFormat>APEX-{0000}</displayFormat>
        <label>Apex Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Log__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <displayFormat>SCP-{0000}</displayFormat>
        <label>Channel Partner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/GST_Registration__c.field-meta.xml
<CustomField>
    <fullName>GST_Registration__c</fullName>
    <label>GST Registration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Owner_Details__c.field-meta.xml
<CustomField>
    <fullName>Owner_Details__c</fullName>
    <label>Owner Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/RERA_Registration__c.field-meta.xml
<CustomField>
    <fullName>RERA_Registration__c</fullName>
    <label>RERA Registration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Work_Address__c.field-meta.xml
<CustomField>
    <fullName>Work_Address__c</fullName>
    <label>Work Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ChannelPartnerRegistration.cls
@RestResource(urlMapping='/CPR/*')
global without sharing class ChannelPartnerRegistration {
   
    @HttpGet
    global static void getChannelPartners(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        Apex_Log__c log = new Apex_Log__c();
        log.Request_Type__c ='HttpGet CP Names';
        List<String> cpNames = new List<String>();
        try{
            String databox = req.requestBody.toString();
            String objectName = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
            log.Request_Type__c ='HttpGet CP Names'+objectName;
            log.Request__c = databox;
            if (objectName == 'CPName') {
                List<Channel_Partner__c> cpList = [SELECT id, Name__c FROM Channel_Partner__c WHERE Active__c = true AND Approval_Status__c = 'Approved'];
                for(Channel_Partner__c cp : cpList){
                    cpNames.add(cp.Name__c);
                }
                String jsonResponse = JSON.serialize(cpNames);
                res.addHeader('Content-Type', 'application/json');
                res.responseBody = Blob.valueOf(jsonResponse);
                res.statusCode = 200; // Set success status code
                log.Response__c = jsonResponse;
                log.Status__c = 'Success';
                return;
            }
        }
        catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            res.statusCode = 500;
            res.responseBody = Blob.valueOf('Internal Server Error');
            log.status__c='FAILED';
            log.Error_Message__c = e.getMessage();
        }
        
        insert log;
        
    } 
    @HttpPost
    global static responseData captureLead(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        Apex_Log__c log = new Apex_Log__c();
        log.Request_Type__c ='HttpPost Channel Partner Registration';
        responseData rd = new responseData();
        try {
            String databox = req.requestBody.toString();
            String objectName = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
            Map<String, Object> cObjMap = (Map<String, Object>) JSON.deserializeUntyped(databox);
            log.Request_Type__c ='HttpPost '+objectName;
            log.Request__c = databox;
            if(objectName == 'CP'){
                String cptype = (String) cObjMap.get('cptype');
                String Name = (String) cObjMap.get('Name');
                String emailId = (String) cObjMap.get('emailId');
                String mobileNumber = (String) cObjMap.get('mobileNumber');
                String alternateNumber = (String) cObjMap.get('alternateNumber');
                String reraRegistration = (String) cObjMap.get('reraRegistration');
                String reraNumber = (String) cObjMap.get('reraNumber');
                String gstRegistration = (String) cObjMap.get('gstRegistration');
                String gstNumber = (String) cObjMap.get('gstNumber');
                String ownerDetails = (String) cObjMap.get('ownerDetails');
                String workAddress = (String) cObjMap.get('workAddress');
                Integer teamSize = (Integer) cObjMap.get('teamSize');
                
                Channel_Partner__c cp = new Channel_Partner__c();
                cp.Type__c = cptype;
                cp.Name__c = Name;
                //cp.Manager_Name__c = managerName;
                cp.Email_Id__c = emailId;
                cp.Phone__c = mobileNumber;
                cp.Alternate_number__c = alternateNumber;
                cp.RERA_Registration__c = reraRegistration;
                cp.GST_Registration__c = gstRegistration;
                cp.Owner_Details__c = ownerDetails;
                cp.Work_Address__c = workAddress;
                cp.Team_Size__c = teamSize;
                cp.GST_Number__c = gstNumber;
                cp.RERA_Number__c = reraNumber;
                insert cp;
                if(cp.Id != null){
                    
                    rd.cpRecordId = cp.Id;
                    rd.message = 'Success';
                    log.status__c='Success';
                    log.Response__c = string.valueof(rd);
                }
            }
        }
        catch(Exception e){
            res.statusCode = 500;
            res.responseBody = Blob.valueOf('Internal Server Error');
            rd.message = 'Error';
            log.status__c='FAILED';
            log.Error_Message__c = e.getMessage();
        }
        insert log;
        return rd;
    } 
    global class responseData{
        public string cpRecordId;
        public string message;
    }
}