force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Block_ID__c.field-meta.xml
<CustomField>
    <fullName>Block_ID__c</fullName>
    <formula>IF(
NOT(ISBLANK(Plot__r.Tower1__c)),
Plot__r.Tower1__c,
Plot__r.Block1__r.Id
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Block ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>Total_Cost_Ex_Leg_Main__c  - Total_received_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Property_TypeFor__c.field-meta.xml
<CustomField>
    <fullName>Property_TypeFor__c</fullName>
    <formula>TEXT(Plot__r.Property_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount__c</fullName>
    <formula>Total_received_Amount__c -  Refunded_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Received Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Booking Approved</fullName>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Agreement Under Process</fullName>
            </value>
            <value>
                <fullName>First Disbursement Under Process</fullName>
            </value>
            <value>
                <fullName>Progressive Collections</fullName>
                <label>Progressive Milestones</label>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Handover</fullName>
            </value>
            <value>
                <fullName>Handed Over</fullName>
            </value>
            <value>
                <fullName>Swapping In Progress</fullName>
            </value>
            <value>
                <fullName>Swapping Completed</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Assignment Progress</fullName>
            </value>
            <value>
                <fullName>Assignment Completed</fullName>
            </value>
            <value>
                <fullName>Agreement</fullName>
                <isActive>false</isActive>
                <label>Agreement</label>
            </value>
            <value>
                <fullName>Booking</fullName>
                <isActive>false</isActive>
                <label>Booking</label>
            </value>
            <value>
                <fullName>D&amp;P</fullName>
                <isActive>false</isActive>
                <label>D&amp;P</label>
            </value>
            <value>
                <fullName>Legal Finalization</fullName>
                <isActive>false</isActive>
                <label>Legal Finalization</label>
            </value>
            <value>
                <fullName>Loan Approval</fullName>
                <isActive>false</isActive>
                <label>Loan Approval</label>
            </value>
            <value>
                <fullName>Maintanance</fullName>
                <isActive>false</isActive>
                <label>Maintanance</label>
            </value>
            <value>
                <fullName>Possession</fullName>
                <isActive>false</isActive>
                <label>Possession</label>
            </value>
            <value>
                <fullName>Swapping</fullName>
                <isActive>false</isActive>
                <label>Swapping</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Welcome call</fullName>
            </value>
            <value>
                <fullName>Legal Process</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Closed won</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
                <isActive>false</isActive>
                <label>Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Payment_Schedule__c/Master_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Master Payment Schedule</label>
    <nameField>
        <label>Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Payment_Schedule__c/fields/Block_Id__c.field-meta.xml
<CustomField>
    <fullName>Block_Id__c</fullName>
    <formula>Block__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Block Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/AmountB__c.field-meta.xml
<CustomField>
    <fullName>AmountB__c</fullName>
    <formula>IF(Is_True_Project_Booking__c == true,Booking__r.Total_Cost_Ex_Leg_Main__c * Payment_percent__c ,
			IF(AND(S_No__c == 1, Name != &apos;Merged Schedules&apos;),
				Booking__r.Booking_Amount__c,
				IF(Booking__r.Property_TypeFor__c = &apos;Villa&apos;,
								IF(S_No__c == 2,
												IF(Master_Payment_Schedule__r.Is_Land__c = true,
																(Booking__r.Land_Cost__c * Payment_percent__c) - Booking__r.Booking_Amount__c,
																Amount__c
												),
												IF(Master_Payment_Schedule__r.Is_Land__c = true,
																Booking__r.Land_Cost__c * Payment_percent__c,
																(Booking__r.Total_Cost_Ex_Leg_Main__c - Booking__r.Land_Cost__c )* Payment_percent__c
												)
								),
								if(S_No__c == 2,  
										 (Booking__r.Total_Cost_Ex_Leg_Main__c * Payment_percent__c) - Booking__r.Booking_Amount__c,
											Booking__r.Total_Cost_Ex_Leg_Main__c * Payment_percent__c)
				)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AmountB</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Block_ID__c.field-meta.xml
<CustomField>
    <fullName>Block_ID__c</fullName>
    <formula>Master_Payment_Schedule__r.Block_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Block ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount__c</fullName>
    <formula>If( Include_Interest__c ,if(Payment_Due_Date__c &lt; TODAY() &amp;&amp;  ISBLANK(Last_Payment_Date__c),
			(AmountB__c *  Interest_Percent__c * (TODAY() - Payment_Due_Date__c))/365 ,
			if(Last_Payment_Date__c &lt; TODAY() &amp;&amp; !ISBLANK(Last_Payment_Date__c),
						(AmountB__c *  Interest_Percent__c * (TODAY() - Last_Payment_Date__c))/365, 0.0)),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Interest_Up_to_Date__c.field-meta.xml
<CustomField>
    <fullName>Interest_Up_to_Date__c</fullName>
    <label>Interest Up to Date</label>
    <summarizedField>Interest_Amount_Line_Items__c.Interest_Amount__c</summarizedField>
    <summaryForeignKey>Interest_Amount_Line_Items__c.Payment_Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Master_Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Master_Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Payment Schedule</label>
    <referenceTo>Master_Payment_Schedule__c</referenceTo>
    <relationshipLabel>Payment schedules</relationshipLabel>
    <relationshipName>Payment_schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Received_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount1__c</fullName>
    <label>Received Amount</label>
    <summarizedField>Receipt_Line_Item__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Approval_Status1__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt_Line_Item__c.Payment_schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <externalId>true</externalId>
    <label>S No</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Demanded</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/Receipt_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Receipt Line Item</label>
    <nameField>
        <label>Receipt Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipt Line Items</relationshipLabel>
    <relationshipName>Receipt_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Payment_schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_schedule__c</fullName>
    <label>Payment schedule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Payment_schedule__c.Booking__c</field>
            <operation>equals</operation>
            <valueField>$Source.Booking__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payment_schedule__c</referenceTo>
    <relationshipLabel>Receipt Line Items</relationshipLabel>
    <relationshipName>Receipt_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RaiseDemandControllerCustom.cls
public class RaiseDemandControllerCustom {
    
    public List<PaymentScheduleWrapper> paymentSchedules { get; set; }
    public Decimal totalAmount { get; set; }
    public Decimal totalPaymentPercent { get; set; }
    public Decimal totalPendingAmount { get; set; }
    public String  totalPendingAmountStr { get; set; }
    public Decimal totalReceivedAmount { get; set; }
    public String totalReceivedAmountInwords { get; set; }
    public Decimal totalInterest {get;set;}
    public String stageName {get;set;}
    public Date demandDueDate {get;set;}

    public class PaymentScheduleWrapper {
        public Decimal SNo { get; set; }
        public String ScheduleName { get; set; }
        public Decimal PaymentPercent { get; set; }
        public Decimal AmountB { get; set; }
        public Decimal PendingAmount { get; set; }
        public Decimal ReceivedAmount { get; set; }
        public Decimal InterestAmount { get; set; }
        public Decimal grandTotal { get; set; }
    }

    public RaiseDemandControllerCustom(ApexPages.StandardController stdController) {
        totalAmount = 0;
        totalPaymentPercent = 0;
        totalPendingAmount = 0;
        totalReceivedAmount = 0;
        totalInterest = 0;
        List<Payment_Schedule__c> schedules;
        // Fetch Booking__c record Id from the PageReference
        Id bookingRecordId = ApexPages.currentPage().getParameters().get('Id');
        Id bookingId = ApexPages.currentPage().getParameters().get('Id');
        String demandAmount = ApexPages.currentPage().getParameters().get('demandAmount');
        Booking__c book = [select id,name,Stage__c,Property_Type__c,Property_TypeFor__c,Block_ID__c from Booking__c where id=:bookingId];
        System.debug('bookingRecordId :' + bookingRecordId);
        System.debug('bookingId :' + bookingId);
        
        if(book.Property_TypeFor__c == 'Apartment'){
            List<Master_Payment_Schedule__c> msList = [select id,name,S_No__c,Due_Date__c,Block_ID__c from Master_Payment_Schedule__c where Status__c = 'Completed' and Block_ID__c =:book.Block_ID__c order by S_No__c desc limit 1];
            if(msList.size() >0){
                stageName = msList[0].name;
                demandDueDate = system.today() + 7;
            }
            /*if(book.Stage__c == 'Progressive Collections'){
List<Master_Payment_Schedule__c> msList = [select id,name,S_No__c,Due_Date__c,Block_ID__c from Master_Payment_Schedule__c where Status__c = 'Completed' and Block_ID__c =:book.Block_ID__c order by S_No__c desc limit 1];
if(msList.size() >0){
                    stageName = msList[0].name;
                    demandDueDate = system.today() + 7;
                }
                else{
                    Payment_Schedule__c pay = [select id,name from Payment_Schedule__c where S_No__c = 2 and Booking__c =: bookingRecordId limit 1];
                    stageName = 'First Disbrusment';
                    demandDueDate = system.today() + 7;
                }
            }
            else {
                Payment_Schedule__c msList = [select id,name,S_No__c,Payment_Due_Date__c from Payment_Schedule__c where  Booking__c =: bookingRecordId and (S_No__c = 1 or S_No__c = 2) order by S_No__c desc limit 1];
                stageName = msList.name;
                demandDueDate = system.today() + 7;
            }*/
            
            if (bookingRecordId != null) {
                // Use the Booking__c record Id in the query
                schedules = [
                    SELECT Id, S_No__c, Pending_Amount__c,Interest_Up_to_Date__c,Is_Demanded__c,Received_Amount1__c,Name, Payment_percent__c, AmountB__c,
                    Master_Payment_Schedule__r.Completed_date__c,Interest_Amount__c, Booking__c
                    FROM Payment_Schedule__c
                    WHERE (Master_Payment_Schedule__r.Status__c = 'Completed') and Pending_Amount__c != 0
                    AND Booking__c = :bookingRecordId
                ];
            }   
            else  if (bookingId != null) {
                // Use the Booking__c record Id in the query
                schedules = [
                    SELECT Id, S_No__c, Name,Pending_Amount__c,Interest_Up_to_Date__c,Received_Amount1__c,Is_Demanded__c,Interest_Amount__c, Payment_percent__c, AmountB__c,
                    Master_Payment_Schedule__r.Completed_date__c, Booking__c
                    FROM Payment_Schedule__c
                    WHERE Master_Payment_Schedule__r.Status__c = 'Completed' and Pending_Amount__c != 0
                    AND Booking__c = :bookingId
                ];
            }   
        }
        else {
            List<Payment_Schedule__c> msList = [select id,name,S_No__c,Payment_Due_Date__c from Payment_Schedule__c where Status__c = 'Completed'  and Booking__c =: bookingRecordId order by S_No__c desc limit 1];
            if(msList.size() >0){
                stageName = msList[0].name;
                system.debug('entered progressive coolection of villa stagename '+stageName);
                demandDueDate = system.today() + 7;
            }
            /*
            if(book.Stage__c == 'Progressive Collections'){
                List<Payment_Schedule__c> msList = [select id,name,S_No__c,Payment_Due_Date__c from Payment_Schedule__c where Status__c = 'Completed' and Payment_Due_Date__c != null order by S_No__c desc limit 1];
                if(msList.size() >0){
                    stageName = msList[0].name;
                    demandDueDate = system.today() + 7;
                }
                else{
                    Payment_Schedule__c pay = [select id,name from Payment_Schedule__c where S_No__c = 2 and Booking__c =: bookingRecordId limit 1];
                    stageName = 'First Disbrusment';
                    demandDueDate = system.today() + 7;
                }
            }
            else {
                Payment_Schedule__c msList = [select id,name,S_No__c,Payment_Due_Date__c from Payment_Schedule__c where  Booking__c =: bookingRecordId and (S_No__c = 1 or S_No__c = 2) order by S_No__c desc limit 1];
                stageName = msList.name;
                demandDueDate = system.today() + 7;
            }*/
            
            if (bookingRecordId != null) {
                // Use the Booking__c record Id in the query
                schedules = [
                    SELECT Id, S_No__c, Pending_Amount__c,Interest_Up_to_Date__c,Is_Demanded__c,Received_Amount1__c,Name, Payment_percent__c, AmountB__c,
                    Master_Payment_Schedule__r.Completed_date__c,Interest_Amount__c, Booking__c
                    FROM Payment_Schedule__c
                    WHERE (Status__c = 'Completed' or S_No__c = 1 or S_No__c = 2) and Pending_Amount__c != 0
                    AND Booking__c = :bookingRecordId
                ];
            }   
            else  if (bookingId != null) {
                // Use the Booking__c record Id in the query
                schedules = [
                    SELECT Id, S_No__c, Name,Pending_Amount__c,Interest_Up_to_Date__c,Received_Amount1__c,Is_Demanded__c,Interest_Amount__c, Payment_percent__c, AmountB__c,
                    Master_Payment_Schedule__r.Completed_date__c, Booking__c
                    FROM Payment_Schedule__c
                    WHERE Status__c = 'Completed' and Pending_Amount__c != 0
                    AND Booking__c = :bookingId
                ];
            }   
            
        }
        

        // Fetch all related Receipt_Line_Item__c records in a single query
        Map<Id, List<Receipt_Line_Item__c>> scheduleToReceiptMap = new Map<Id, List<Receipt_Line_Item__c>>();
        for (Receipt_Line_Item__c receiptLineItem : [SELECT Id, Pending_Amount__c, Received_Amount__c, Payment_Schedule__c FROM Receipt_Line_Item__c WHERE Payment_Schedule__c IN :schedules]) {
            if (!scheduleToReceiptMap.containsKey(receiptLineItem.Payment_Schedule__c)) {
                scheduleToReceiptMap.put(receiptLineItem.Payment_Schedule__c, new List<Receipt_Line_Item__c>());
            }
            scheduleToReceiptMap.get(receiptLineItem.Payment_Schedule__c).add(receiptLineItem);
        }

        // Populate PaymentScheduleWrapper list
        paymentSchedules = new List<PaymentScheduleWrapper>();
        for (Payment_Schedule__c schedule : schedules) {
            PaymentScheduleWrapper wrapper = new PaymentScheduleWrapper();
            wrapper.SNo = schedule.S_No__c;
            wrapper.ScheduleName = schedule.Name;
            wrapper.PaymentPercent = (schedule.Payment_percent__c != null) ? schedule.Payment_percent__c : 0;
            wrapper.AmountB = (schedule.AmountB__c != null) ? schedule.AmountB__c : 0;
            Decimal InterestAmount = 0;
            if(schedule.Interest_Up_to_Date__c == 0){
                InterestAmount = schedule.Interest_Amount__c;
            }
            else{
                InterestAmount = schedule.Interest_Up_to_Date__c + schedule.Interest_Amount__c;
            }
            //wrapper.InterestAmount = (schedule.Interest_Up_to_Date__c != 0) ? schedule.Interest_Up_to_Date__c : schedule.Interest_Amount__c;
            Decimal pendingAmount1 = schedule.Pending_Amount__c;
            Decimal receivedAmount = schedule.Received_Amount1__c;
 
            // Use the map to get related Receipt_Line_Item__c records without additional queries
            /*if (scheduleToReceiptMap.containsKey(schedule.Id)) {
                for (Receipt_Line_Item__c receiptLineItem : scheduleToReceiptMap.get(schedule.Id)) {
                    pendingAmount += (receiptLineItem.Pending_Amount__c != null) ? receiptLineItem.Pending_Amount__c : 0;
                    totalPendingAmount += (receiptLineItem.Pending_Amount__c != null) ? receiptLineItem.Pending_Amount__c : 0;

                    receivedAmount += (receiptLineItem.Received_Amount__c != null) ? receiptLineItem.Received_Amount__c : 0;
                    totalReceivedAmount += (receiptLineItem.Received_Amount__c != null) ? receiptLineItem.Received_Amount__c : 0;
                }
            }*/
            system.debug('dbhdbhdbhhv     '+InterestAmount);
            wrapper.PendingAmount = pendingAmount1;
            wrapper.ReceivedAmount = receivedAmount;
            wrapper.InterestAmount = InterestAmount;
            paymentSchedules.add(wrapper);
            
            // Update totals
            totalAmount += wrapper.AmountB;
            totalPaymentPercent += wrapper.PaymentPercent;
            totalReceivedAmount += wrapper.ReceivedAmount;
            totalPendingAmount += wrapper.PendingAmount;
            Decimal decimalValue = Decimal.valueOf(demandAmount);
            totalPendingAmountStr = decimalValue.setScale(2).format();
            NumberTOWordConvertion nwcObj = new NumberTOWordConvertion();
            totalReceivedAmountInwords = nwcObj.getNumberTOWordConvertion(decimalValue);
            system.debug('dbhdbhdbhhv     '+wrapper.InterestAmount);
            system.debug('totalInterest     '+totalInterest);
            totalInterest += wrapper.InterestAmount;
        }
    }
    public void testMentod(){
        integer i=0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
    }

}