force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/EB_GST_18__c.field-meta.xml
<CustomField>
    <fullName>EB_GST_18__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <formula>Total_Cost_Ex_Leg_Main__c *  GST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Labour_Cess__c.field-meta.xml
<CustomField>
    <fullName>Labour_Cess__c</fullName>
    <formula>IF(ISPICKVAL(Property_Type__c,&apos;Villa&apos;),0,(Basic_Price__c  * 0.7)/100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Labour Cess</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>Total_Cost_Ex_Leg_Main__c  - Total_received_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Sanctioned_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sanctioned_Amount__c</fullName>
    <label>Loan Sanctioned Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Cost_Ex_Leg_Main__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_Ex_Leg_Main__c</fullName>
    <label>Total Cost (Ex. Leg.,Reg &amp; Main.)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Cost_Excluding_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_Excluding_Tax__c</fullName>
    <formula>Total_Cost_Ex_Leg_Main__c -  GST_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost Excluding Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Cost_With_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_With_Tax__c</fullName>
    <formula>Quote__r.Grand_Total_Amount_With_Tax__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost With Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_received_Amount__c</fullName>
    <label>Total Receipt Amount</label>
    <summarizedField>Receipt__c.Total_Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt__c.Approval_status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/Amount1__c.field-meta.xml
<CustomField>
    <fullName>Amount1__c</fullName>
    <formula>IF(Is_True_Project__c == true,Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c * Payment_percent__c ,IF(
					S_No__c == 1,
					Quote__r.Booking_AmountNew__c,
					IF(
									Quote__r.Property_Type_For__c = &apos;Villa&apos;,
									IF(
													S_No__c == 2,
													IF(
																	Master_Payment_Schedule__r.Is_Land__c = true,
																	((Quote__r.Land_Cost__c * Payment_percent__c)) - Quote__r.Booking_AmountNew__c,
																	Amount__c
													),
													IF(
																	Master_Payment_Schedule__r.Is_Land__c = true,
																	Quote__r.Land_Cost__c * Payment_percent__c,
																	(Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c - Quote__r.Land_Cost__c) * Payment_percent__c

													)
									),
									if(S_No__c == 2, ((Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c * Payment_percent__c ) - Quote__r.Booking_AmountNew__c),Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c * Payment_percent__c)
					)
	))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NUAmount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/AmountB__c.field-meta.xml
<CustomField>
    <fullName>AmountB__c</fullName>
    <formula>IF(Is_True_Project_Booking__c == true,Booking__r.Total_Cost_Ex_Leg_Main__c * Payment_percent__c ,
			IF(AND(S_No__c == 1, Name != &apos;Merged Schedules&apos;),
				Booking__r.Booking_Amount__c,
				IF(Booking__r.Property_TypeFor__c = &apos;Villa&apos;,
								IF(S_No__c == 2,
												IF(Master_Payment_Schedule__r.Is_Land__c = true,
																(Booking__r.Land_Cost__c * Payment_percent__c) - Booking__r.Booking_Amount__c,
																Amount__c
												),
												IF(Master_Payment_Schedule__r.Is_Land__c = true,
																Booking__r.Land_Cost__c * Payment_percent__c,
																(Booking__r.Total_Cost_Ex_Leg_Main__c - Booking__r.Land_Cost__c )* Payment_percent__c
												)
								),
								if(S_No__c == 2,  
										 (Booking__r.Total_Cost_Ex_Leg_Main__c * Payment_percent__c) - Booking__r.Booking_Amount__c,
											Booking__r.Total_Cost_Ex_Leg_Main__c * Payment_percent__c)
				)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AmountB</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Booking_Amount__c.field-meta.xml
<CustomField>
    <fullName>Booking_Amount__c</fullName>
    <formula>Booking__r.Booking_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Booking Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Is_Construction__c.field-meta.xml
<CustomField>
    <fullName>Is_Construction__c</fullName>
    <formula>Master_Payment_Schedule__r.Is_Construction__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Construction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Is_Land__c.field-meta.xml
<CustomField>
    <fullName>Is_Land__c</fullName>
    <formula>Master_Payment_Schedule__r.Is_Land__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Land</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <externalId>true</externalId>
    <label>S No</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plot__c/Plot__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot__c/fields/Basic_Price__c.field-meta.xml
<CustomField>
    <fullName>Basic_Price__c</fullName>
    <label>Basic Price Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Labour_Cess__c.field-meta.xml
<CustomField>
    <fullName>Labour_Cess__c</fullName>
    <formula>IF(ISPICKVAL(Property_Type__c, &apos;Apartment&apos;), Total_Cost__c * Project__r.Labour_Cess__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Labour Cess</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Land_Cost__c.field-meta.xml
<CustomField>
    <fullName>Land_Cost__c</fullName>
    <formula>Land_Rate_per_sqft__c * Plot_Land_Area__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Land Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Plots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Total_Cost_Ex_Leg_Main__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_Ex_Leg_Main__c</fullName>
    <formula>Total_Cost__c  +  GST__c + Labour_Cess__c+ Other_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost (Ex. Leg. &amp; Main.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Labour_Cess__c.field-meta.xml
<CustomField>
    <fullName>Labour_Cess__c</fullName>
    <label>Labour Cess</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Specification__c.field-meta.xml
<CustomField>
    <fullName>Project_Specification__c</fullName>
    <label>Project Specification</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/convertValueToWords.cls
public class convertValueToWords {
    public Id bookingId;
    public string totalPendingInIndia{get;set;}
    public string totalPendingWords{get;set;}
    public string totalCostInString{get;set;}
    public string loanAmountInString{get;set;}
    public string loanAmountInWords{get;set;}
    public string tillDateReceived{get;set;}
    public string TotalCostAmountInWords{get;set;}
    public string TotalBasicAmountInWords{get; set;}
    public string BookingAmount{get;set;}
    public string projectSpecification {get;set;}
    public String totlreceivedinIndian {get;set;}
    public String totlbasicPriceinIndian {get;set;}
    public String totltaxinIndian {get;set;}
    Public String WhiperingTotalAmount{get; set;}
    public String totalExcludingTaxInIndian {get;set;}
    public String TotalExcludingTaxInWords {get;set;}
    public String totalWithTaxInIndian {get;set;}
    public String landCostInIndian {get;set;}
    public String gstAmountInIndian {get;set;}
    public String labourCessInIndian {get;set;}
    
    public List<paySchWrapper> payList {get;set;}
    
    public class paySchWrapper{
        public string Name{get;set;}
        public Decimal Payment_percent{get;set;}
        public boolean isConstruction{get;set;}
        public boolean isSale{get;set;}
        public string amount{get;set;}
        Public string whisperingAmount{get; set;}
        public Decimal S_No{get;set;}
    }
    
    public convertValueToWords(ApexPages.StandardController stdController) {
        bookingId = (Id)stdController.getId();
        Booking__c bk = [select id,name,Plot__c,Project__c,EB_GST_18__c,Labour_Cess__c,Basic_Price__c,Total_received_Amount__c,Total_Cost_Ex_Leg_Main__c,Booking_Amount__c,Sanctioned_Amount__c,Pending_Amount__c,Total_Cost_Excluding_Tax__c,Total_Cost_With_Tax__c,Land_Cost__c,GST_Amount__c from Booking__c where id =: bookingId];
        if(bk.Project__c != null){
            List<Project__c> prj = [select id,name,Project_Specification__c from Project__c where Project__c =: bk.Project__c];
            if(prj.size() >0){
                projectSpecification = prj[0].Project_Specification__c;
            }
            
        }
        List<paySchWrapper> samp = new List<paySchWrapper>();
        List<Payment_Schedule__c> payListStan = [select id,name,S_No__c,Payment_Percent__c,AmountB__c,Amount1__c,Amount__c,Is_Land__c, Is_Construction__c from Payment_Schedule__c where Booking__c =:bk.id ];
        for(Payment_Schedule__c ps : payListStan){
            paySchWrapper pw = new paySchWrapper();
            pw.Name = ps.Name;
            pw.Payment_percent = ps.Payment_Percent__c;
            pw.isConstruction = ps.Is_Construction__c;
            pw.isSale = ps.Is_Land__c;
            pw.amount = ps.AmountB__c != null ? ps.AmountB__c.setScale(2).format() : '';
            pw.whisperingAmount = (bk.Basic_Price__c != null && ps.Payment_Percent__c != null) ? (bk.Basic_Price__c * ps.Payment_Percent__c / 100).setScale(2).format() : '';
            pw.S_No = ps.S_No__c;
            samp.add(pw);
        }

		payList =  samp;
        if(bk.EB_GST_18__c != null && bk.Labour_Cess__c != null){
            Decimal totalTax = Math.round(bk.EB_GST_18__c + bk.Labour_Cess__c);
            totltaxinIndian = totalTax.setScale(2).format();
        }
        totalCostInString = bk.Total_Cost_Ex_Leg_Main__c != null ? bk.Total_Cost_Ex_Leg_Main__c.setScale(2).format() : '';
        totlreceivedinIndian = bk.Total_received_Amount__c != null ? bk.Total_received_Amount__c.setScale(2).format() : '';
        totalPendingInIndia = bk.Pending_Amount__c != null ? bk.Pending_Amount__c.setScale(2).format() : '';
        NumberTOWordConvertion nwcObj = new NumberTOWordConvertion();
        if(bk.Sanctioned_Amount__c != null){
            loanAmountInString = bk.Sanctioned_Amount__c.setScale(2).format();
            loanAmountInWords = nwcObj.getNumberTOWordConvertion(bk.Sanctioned_Amount__c);
        }
        if(bk.Basic_Price__c != null){
            totlbasicPriceinIndian = bk.Basic_Price__c.setScale(2).format();
        }
        TotalCostAmountInWords = bk.Total_Cost_Ex_Leg_Main__c != null ? nwcObj.getNumberTOWordConvertion(bk.Total_Cost_Ex_Leg_Main__c) : '';
        TotalBasicAmountInWords = bk.Basic_Price__c != null ? nwcObj.getNumberTOWordConvertion(bk.Basic_Price__c) : '';
        BookingAmount = bk.Booking_Amount__c != null ? nwcObj.getNumberTOWordConvertion(bk.Booking_Amount__c) : '';
        totalPendingWords = bk.Pending_Amount__c != null ? nwcObj.getNumberTOWordConvertion(bk.Pending_Amount__c) : '';
        tillDateReceived = bk.Total_received_Amount__c != null ? nwcObj.getNumberTOWordConvertion(bk.Total_received_Amount__c) : '';
        totalExcludingTaxInIndian = bk.Total_Cost_Excluding_Tax__c != null ? bk.Total_Cost_Excluding_Tax__c.setScale(2).format() : '';
        TotalExcludingTaxInWords = bk.Total_Cost_Excluding_Tax__c != null ? nwcObj.getNumberTOWordConvertion(bk.Total_Cost_Excluding_Tax__c) : '';
        totalWithTaxInIndian = bk.Total_Cost_With_Tax__c != null ? bk.Total_Cost_With_Tax__c.setScale(2).format() : '';
        landCostInIndian = bk.Land_Cost__c != null ? bk.Land_Cost__c.setScale(2).format() : '';
        gstAmountInIndian = bk.GST_Amount__c != null ? bk.GST_Amount__c.setScale(2).format() : '';
        labourCessInIndian = bk.Labour_Cess__c != null ? bk.Labour_Cess__c.setScale(2).format() : '';
    }

}