force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Welcome call</fullName>
            </value>
            <value>
                <fullName>Legal Process</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Closed won</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
                <isActive>false</isActive>
                <label>Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Follow_up__c/Follow_up__c.object-meta.xml
<CustomObject>
    <label>Follow up</label>
    <nameField>
        <displayFormat>F-{000}</displayFormat>
        <label>Follow up Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_up__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZLead</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Follow ups</relationshipLabel>
    <relationshipName>Follow_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <defaultValue>&apos;Follow Up&apos;</defaultValue>
    <label>Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateBookingFormController.cls
public class UpdateBookingFormController {
    
    @AuraEnabled
    public static void updateBookingStatus(String recordId) {
        
        system.debug('record id === '+ RecordId);
        Booking__c book=[select id,Name ,Followup_Date__c,Followup_Subject__c,Status__c,Sub_Status__c,Last_comment__c,Lead__r.Id from Booking__c where Id =: recordId Limit 1];
        if(book.Last_Comment__c!=null){
            Task logTask =  new Task(
                Subject = 'Call',
                ActivityDate = system.today(),
                status='Completed',
                Description=book.Last_Comment__c,
                tasksubtype='Call',
                whatid = book.Id);
            insert logTask;
            system.debug('logTask == '+ logTask);
        }
        
        
        if(book.Followup_Date__c!=null && book.Followup_Subject__c !=null && book.Status__c!='Cancellation' && book.Status__c!='Closed won'){
            List<Follow_up__c> followUp = [SELECT Id,OwnerId,Scheduled_Date__c,Name,Booking__c FROM Follow_up__c WHERE Booking__c=:book.Id AND ownerId=:userinfo.getUserId() AND Scheduled_Date__c=:book.Followup_Date__c LIMIT 1];
            if(followUp.size()==0){
                Follow_up__c logTask =  new Follow_up__c(
                    Subject__c = book.Followup_Subject__c,
                    Scheduled_Date__c =book.Followup_Date__c,
                    Booking__c = book.Id);
                insert logTask;
                system.debug('logTask == '+logTask);
            }else{
                followUp[0].Subject__c = book.Followup_Subject__c;
                update followUp[0];
                system.debug('Task == '+followUp[0]);
            }
            
            
        }
        
    }
    
     @AuraEnabled
    public static void sendEmail(String recordId) {
        
        system.debug('record id === '+ RecordId);
        Booking__c book=[select id,Name ,Followup_Date__c,Followup_Subject__c,Status__c,Sub_Status__c,Last_comment__c,Lead__r.Id from Booking__c where Id =: recordId Limit 1];
        if(book.Status__c =='Welcome call' && book.Sub_Status__c =='Positive'){
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                String[] sendingTo = new String[]{'test@fingertipplus.com'};
                    email.setToAddresses(sendingTo);
                String[] sendingToBccAdd = new String[]{'test@fingertipplus.com'};
                    email.setBccAddresses(sendingToBccAdd);
                String[] sendingTocAdd = new String[]{'test@fingertipplus.com'};
                    email.setCcAddresses(sendingTocAdd);
                email.setSubject('Single Email message Example');
                email.setPlainTextBody('Test Message');
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
                system.debug('email == '+email);                
            }
    }
}