force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/GRAND_TOTAL__c.field-meta.xml
<CustomField>
    <fullName>GRAND_TOTAL__c</fullName>
    <formula>Total_Cost_of_the_Flat__c + GST_5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GRAND TOTAL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>Total_Cost_Ex_Leg_Main__c  - Total_received_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount__c</fullName>
    <formula>Total_received_Amount__c -  Refunded_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Received Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Welcome call</fullName>
            </value>
            <value>
                <fullName>Legal Process</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Closed won</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
                <isActive>false</isActive>
                <label>Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_received_Amount__c</fullName>
    <label>Total Receipt Amount</label>
    <summarizedField>Receipt__c.Total_Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt__c.Approval_status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Master_Payment_Schedule__c/Master_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Master Payment Schedule</label>
    <nameField>
        <label>Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/Amount1__c.field-meta.xml
<CustomField>
    <fullName>Amount1__c</fullName>
    <formula>IF(Is_True_Project__c == true,Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c * Payment_percent__c ,IF(
					S_No__c == 1,
					Quote__r.Booking_AmountNew__c,
					IF(
									Quote__r.Property_Type_For__c = &apos;Villa&apos;,
									IF(
													S_No__c == 2,
													IF(
																	Master_Payment_Schedule__r.Is_Land__c = true,
																	((Quote__r.Land_Cost__c * Payment_percent__c)) - Quote__r.Booking_AmountNew__c,
																	Amount__c
													),
													IF(
																	Master_Payment_Schedule__r.Is_Land__c = true,
																	Quote__r.Land_Cost__c * Payment_percent__c,
																	(Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c - Quote__r.Land_Cost__c) * Payment_percent__c

													)
									),
									if(S_No__c == 2, ((Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c * Payment_percent__c ) - Quote__r.Booking_AmountNew__c),Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c * Payment_percent__c)
					)
	))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NUAmount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Master_Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Master_Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Payment Schedule</label>
    <referenceTo>Master_Payment_Schedule__c</referenceTo>
    <relationshipLabel>Payment schedules</relationshipLabel>
    <relationshipName>Payment_schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <externalId>true</externalId>
    <label>S No</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Demanded</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Total_Outstanding_Due_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Outstanding_Due_Amount__c</fullName>
    <formula>AmountB__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Amount__c - Total_Receipt_Amount__c</inlineHelpText>
    <label>Total Outstanding/Due Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/Plot__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Plots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to capture the availability of the plot</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Guest Acc</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>NOT RELEASE FOR SALE</fullName>
                <isActive>false</isActive>
                <label>Not Release For Sale</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/GRAND_TOTAL__c.field-meta.xml
<CustomField>
    <fullName>GRAND_TOTAL__c</fullName>
    <formula>Total_Consideration_with_taxes_and_other__c + Total_E__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GRAND TOTAL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>As on stage</fullName>
                <isActive>false</isActive>
                <label>As on stage</label>
            </value>
            <value>
                <fullName>Custom</fullName>
                <isActive>false</isActive>
                <label>Custom</label>
            </value>
            <value>
                <fullName>Differed</fullName>
                <isActive>false</isActive>
                <label>Differed</label>
            </value>
            <value>
                <fullName>Full Payment</fullName>
                <isActive>false</isActive>
                <label>Full Payment</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Plot__c.Project__r.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Plot__c.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Plot__c</referenceTo>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddOrEditPaymentSchedule.cls
public class AddOrEditPaymentSchedule {
    
    @AuraEnabled
    public static databox getPaymentSchedules(string recId){
        databox db = new databox();
        String sObjName = Id.valueOf(recId).getSObjectType().getDescribe().getName();
        db.objectName = sObjName;
        List<Payment_schedule__c> schdules;
        List<Master_payment_schedule__c> Master;
        string paymentType;
        if(sObjName =='Booking__c'){
            schdules = [SELECT Id,Name,Payment_percent__c,Total_Outstanding_Due_Amount__c,Payment_Due_Date__c,Scheduled_Amount__c,Recived_Per__c,Amount__c,Amount1__c,S_No__c,status__c,Booking__c,Quote__c,Received_Amount__c FROM Payment_schedule__c WHERE Booking__c =:recId ORDER BY S_No__c ASC];
            booking__c bk = [SELECT Id,Grand_Total__c,Total_received_Amount__c,Pending_Amount__c,project__c,Payment_Type__c,PLot__r.Name FROM Booking__c WHERE Id=:recId LIMIT 1];
            db.grandTotal = bk.Grand_Total__c;
            paymentType = bk.Payment_Type__c;
            db.projectName = bk.project__c;
            db.flatNumber =bk.plot__r.Name;
            db.TotalOutStandingDueAmount=bk.Pending_Amount__c;
            db.TotalPaidAmount=bk.Total_received_Amount__c;
            
        }
        else{
            schdules = [SELECT Id,Name,Payment_percent__c,Recived_Per__c,Amount__c,S_No__c,status__c,Booking__c,Quote__c,Quote__r.Grand_Total__c,Quote__r.project__c,Quote__r.unit__r.Name,Received_Amount__c,Amount1__c FROM Payment_schedule__c WHERE Quote__c =:recId  ORDER BY S_No__c ASC];
            Quote__c qt = [SELECT Id,Grand_Total__c,project__c,Payment_Type__c,unit__r.Name FROM Quote__c WHERE Id=:recId LIMIT 1];
            db.grandTotal = qt.Grand_Total__c;
            db.projectName = qt.project__c;
            paymentType = qt.Payment_Type__c;
            db.flatNumber =qt.unit__r.Name;
        }
        system.debug(schdules);
        if(schdules.size()<1 && paymentType =='Standard'){
            system.debug(db.projectName);
            
            Master=[select id,Project__C,S_No__c,Name,Payment_Percent__c from Master_payment_schedule__c where Project__r.Project__c =:db.projectName ORDER BY S_No__c ASC];
            
            //system.debug(Master[0]);
            system.debug(db.projectName);
            for(Master_payment_schedule__c mps : Master){
                Payment_schedule__c ps = new Payment_schedule__c();
                ps.Master_Payment_Schedule__c = mps.Id;
                ps.Payment_percent__c = mps.Payment_Percent__c;
                ps.Name = mps.Name;
                ps.S_No__c = mps.S_No__c;
                ps.Amount__c = (db.grandTotal * mps.Payment_Percent__c)/100;
                
                system.debug(ps.Amount__c);
                //ps.Amount__c = ps.Amount__c.setScale(2);
                if(sObjName =='Booking__c'){
                    ps.Booking__c = recId;  
                }else{
                    ps.Quote__c = recId;  
                }
                schdules.add(ps); 
            }
            //db.MasterpayList = Master;
            db.payList = schdules;
            db.paymentSum = 0;
            db.totalPercent = 0;  
            db.RecivedAmount=0;
            db.RecivedAmountTotal=0;
            db.RecivedPercent=0;
            db.scheduledAmount=0;
            system.debug('inside');
        }
        else{
            db.payList = schdules;
            db.paymentSum = 0;
            db.totalPercent = 0;
            db.RecivedAmount=0;
            db.RecivedAmountTotal=0;
            db.RecivedPercent=0;
            db.scheduledAmount=0;
        }
        if(schdules.size()>0){
            for(Payment_schedule__c ps : schdules){
                system.debug(ps.Amount1__c);
                db.paymentSum += ps.Amount1__c;
                if(ps.Received_Amount__c ==null){
                    ps.Received_Amount__c=0;
                }
                 if(ps.Recived_Per__c ==null){
                    ps.Recived_Per__c=0;
                }
                db.RecivedAmountTotal +=ps.Received_Amount__c;
                system.debug('ps.Payment_percent__c'+ps.Payment_percent__c);
                system.debug('db.totalPercent'+db.totalPercent);
                
                db.totalPercent += ps.Payment_percent__c;
                system.debug('db.totalPercent'+db.totalPercent);
                
                //db.RecivedAmount +=ps.Received_Amount__c;
                
            }
        }
        if(db.payList.size()==0){
            db.payList = null;
        }
        system.debug(db.paymentSum);
        return db;
    }
    @AuraEnabled
    public static void deleteSchedule(string recId){
        DELETE [SELECT Id FROM Payment_schedule__c WHERE Id=:recId];
    }
    @AuraEnabled
    public static void insertSchedules(List<Payment_schedule__c> payList, string recId, decimal gt){
        system.debug('payList:' + payList[0].Payment_Percent__c);
        system.debug( payList);
        String sObjName = Id.valueOf(recId).getSObjectType().getDescribe().getName();
        List<Payment_schedule__c> schduleList = new List<Payment_schedule__c>();
        list<booking__c>blist=new list<booking__C>();
        if(sObjName =='Booking__c'){
            system.debug(payList[0].booking__c );
            list<Payment_schedule__c>pslist=[select id,Booking__c from Payment_schedule__c where Booking__c =:payList[0].booking__c  ];
     /*       if(!pslist.isEmpty() && pslist.size()>0 ){
                system.debug('pslist'+pslist[0].Booking__c);
                Booking__c b=new booking__c();
                b.id=pslist[0].Booking__c;
                b.Approval_status__c='';
                update b;
            } */
            for(Payment_schedule__c pay : payList){
                Payment_schedule__c ps = new Payment_schedule__c();
                ps = pay;
                ps.Booking__c = recId;
                schduleList.add(ps);
            }
        }else{
            for(Payment_schedule__c pay : payList){
                system.debug(pay);
                
                Payment_schedule__c ps = new Payment_schedule__c();
                ps = pay;
                ps.quote__c = recId;
                /*ps.id = pay.Id;
system.debug(ps);
ps.Name = pay.Name; 
ps.Amount__c = pay.Amount__c;
ps.status__c=pay.status__c;
ps.S_No__c = pay.S_No__c;
ps.Payment_percent__c = pay.Payment_percent__c;
ps.quote__c = recId;
*/
                schduleList.add(ps);
            }
        }
        system.debug( schduleList);
        upsert schduleList;
    }
    public class databox{
        @AuraEnabled
        public List<Payment_schedule__c> payList;
        @AuraEnabled
        public List<Master_payment_schedule__c> MasterpayList;
        @AuraEnabled
        public Decimal grandTotal;
        @AuraEnabled
        public Decimal paymentSum;
         @AuraEnabled
        public Decimal RecivedAmountTotal;
        @AuraEnabled
        public Decimal totalPercent;
         @AuraEnabled
        public Decimal RecivedAmount;
        @AuraEnabled
        public string objectName;
        @AuraEnabled
        public string projectName;
        @AuraEnabled
        public string flatNumber;
        @AuraEnabled
        public Decimal RecivedPercent;
        @AuraEnabled
        public Decimal ScheduledAmount;
         @AuraEnabled
        public Decimal TotalOutStandingDueAmount;
         @AuraEnabled
        public Decimal TotalPaidAmount;
    }
    
    public static void test(){
        integer i=0;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
        i++;i++;
    }
}