force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>Total_Cost_Ex_Leg_Main__c  - Total_received_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Cost_Ex_Leg_Main__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_Ex_Leg_Main__c</fullName>
    <label>Total Cost (Ex. Leg.,Reg &amp; Main.)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <externalId>true</externalId>
    <label>S No</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/demandController.cls
public class demandController {
    public Id bookingRecord;
    public decimal paymentPercent {get;set;}
    public decimal paymentAmount {get;set;}
    public String paymentAmountStr {get;set;}
    public decimal Totalcost {get;set;}
    public String TotalcostStr {get;set;}
    public String AmountInWords {get;set;}
    public String AmountInWordsss {get;set;}
    
    public demandController(ApexPages.StandardController stdController) {
        bookingRecord = (Id)stdController.getId();
        //getAgreementAmount();
        getTotalCost();
    }
    
   /* public void getAgreementAmount(){        
        Payment_schedule__c paySchLst = [SELECT Id, Name, Amount__c, Payment_percent__c, Pending_Amount__c FROM Payment_schedule__c WHERE Booking__c = :bookingRecord AND S_No__c = 2 LIMIT 1];
        if (paySchLst != null) {
            paymentPercent = paySchLst.Payment_percent__c;
            paymentAmount = Math.round(paySchLst.Pending_Amount__c);
            paymentAmountStr = paymentAmount.setScale(2).format();
            NumberTOWordConvertion nwcObj = new NumberTOWordConvertion();
            AmountInWordsss = nwcObj.getNumberTOWordConvertion(paymentAmount);
        }
    }*/
    public void getTotalCost(){        
        Booking__c BcLst = [SELECT Id, Name, Total_Cost_Ex_Leg_Main__c FROM  Booking__c where Id = :bookingRecord];
        if (BcLst != null) {
            Totalcost = Math.round(BcLst.Total_Cost_Ex_Leg_Main__c);
            TotalcostStr = Totalcost.setScale(2).format();
             NumberTOWordConvertion nwcObj = new NumberTOWordConvertion();
            AmountInWords = nwcObj.getNumberTOWordConvertion(Totalcost);
        }
    }
}