force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Email_id__c.field-meta.xml
<CustomField>
    <fullName>Email_id__c</fullName>
    <label>Not Used</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Finance_User__c.field-meta.xml
<CustomField>
    <fullName>Finance_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Legal_Team__c.field-meta.xml
<CustomField>
    <fullName>Legal_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Team</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookings4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookings5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Welcome call</fullName>
            </value>
            <value>
                <fullName>Legal Process</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Closed won</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
                <isActive>false</isActive>
                <label>Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Cost_Ex_Leg_Main__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_Ex_Leg_Main__c</fullName>
    <label>Total Cost (Ex. Leg.,Reg &amp; Main.)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <externalId>true</externalId>
    <label>S No</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Demanded</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProjectsiFmw</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>Rc-{000}</displayFormat>
        <label>Receipt  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt_Line_Item__c/Receipt_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Receipt Line Item</label>
    <nameField>
        <label>Receipt Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Approval_Status1__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status1__c</fullName>
    <label>Approval Status Actual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <formula>ISPICKVAL(Receipt__r.Approval_status__c, &apos;Approved&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approval Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipt Line Items</relationshipLabel>
    <relationshipName>Receipt_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Payment_schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_schedule__c</fullName>
    <label>Payment schedule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Payment_schedule__c.Booking__c</field>
            <operation>equals</operation>
            <valueField>$Source.Booking__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payment_schedule__c</referenceTo>
    <relationshipLabel>Receipt Line Items</relationshipLabel>
    <relationshipName>Receipt_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Receipt Line Items</relationshipLabel>
    <relationshipName>Receipt_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ConsolidatedReceiptControllerTest.cls
@isTest
public class ConsolidatedReceiptControllerTest {
    
    public static testmethod void raisedemand(){
        
        Booking__c bk=new Booking__c();
        
        bk.Status__c = 'Welcome call';
        bk.Project__c = 'Test Project';
        bk.Last_comment__c='sampletest comment';
        bk.Followup_Date__c = system.today().addDays(1);
        bk.Followup_Subject__c = 'test';
        bk.Status__c = 'Welcome call';
        bk.Sub_Status__c = 'Positive';
        bk.Total_Cost_Ex_Leg_Main__c = 1000000000;
        bk.Email__c = userinfo.getuserEmail();
        bk.Email_id__c = userinfo.getuserEmail();
        bk.Email__c = userinfo.getuserEmail();
        bk.Legal_Team__c = userinfo.getuserid();
        bk.Finance_User__c = userinfo.getuserid();
        bk.Sales_Manager__c = userInfo.getUserId();
        insert bk;
        
        Payment_schedule__c pay = new Payment_schedule__c();
        pay.Booking__c = bk.id;
        pay.Payment_percent__c = 20;
        pay.Amount__c = 10000;
        pay.S_No__c = 2;
        pay.name = 'Test';
        insert pay;
        
        Receipt__c rc = New Receipt__c();
        rc.Approval_status__c = 'Approved';
        rc.Booking__c = bk.id;
        rc.Finance_user__c = UserInfo.getUserId();
        insert rc;
        List<Receipt_Line_Item__c> reclList = new List<Receipt_Line_Item__c>();
        Receipt_Line_Item__c rci = new Receipt_Line_Item__c();
        rci.Amount__c = 1200;
        rci.Approval_Status1__c = 'Approved';
        rci.Booking__c = bk.id;
        rci.Receipt__c = rc.Id;
        rci.Payment_schedule__c = pay.Id;
        insert rci;
        test.starttest();
        PageReference testPage = Page.Demand_letter; 
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', String.valueOf(bk.Id));
        
        ApexPages.StandardController sc = new  ApexPages.StandardController(bk);     
        ConsolidatedReceiptController ext = new ConsolidatedReceiptController(sc);
        
        test.stoptest();
        
    }

}