force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Email_id__c.field-meta.xml
<CustomField>
    <fullName>Email_id__c</fullName>
    <label>Not Used</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Finance_User__c.field-meta.xml
<CustomField>
    <fullName>Finance_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <formula>TEXT( SLead__r.Lead_source__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Legal_Team__c.field-meta.xml
<CustomField>
    <fullName>Legal_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Team</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookings4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookings5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Welcome call</fullName>
            </value>
            <value>
                <fullName>Legal Process</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Closed won</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
                <isActive>false</isActive>
                <label>Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProjectsiFmw</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>Rc-{000}</displayFormat>
        <label>Receipt  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfer__c/Transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Transfer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BookingWelcomeMailTest.cls
@isTest
public class BookingWelcomeMailTest {
    public static testmethod void Bookingpdf(){
        
        Project__c pro = new Project__c();
        pro.name = 'Test Project';
        pro.Project__c = 'Test Project';
        insert pro;
        lead ld = new lead();
         ld.LastName = 'Test ld';
         ld.Phone__c = '9988776655';
         ld.Lead_source__c = 'Website';
         ld.Email__c = userinfo.getuseremail();
         ld.Allocated_Project__c ='Test Project';
        ld.Lead_source__c = 'Website';
         ld.Lead_Assigned__c =true;
         insert ld;
        Booking__c bk=new Booking__c();
         bk.Slead__c = ld.Id;
        bk.Status__c = 'Welcome call';
        bk.Project__c = 'Test Project';
        bk.Last_comment__c='sampletest comment';
          bk.Followup_Date__c = system.today().addDays(1);
          bk.Followup_Subject__c = 'test';
          bk.Status__c = 'Welcome call';
          bk.Sub_Status__c = 'Positive';
          bk.Email__c = userinfo.getuserEmail();
          bk.Email_id__c = userinfo.getuserEmail();
         bk.Email__c = userinfo.getuserEmail();
        bk.Legal_Team__c = userinfo.getuserid();
        bk.Finance_User__c = userinfo.getuserid();
        bk.Sales_Manager__c = userinfo.getuserid();
        insert bk;
        Receipt__c rc = New Receipt__c();
        rc.Receipt_Name__c = 'Booking Amount Receipt';
        rc.Approval_status__c = 'Approved';
        rc.Booking__c = bk.id;
        rc.Finance_user__c = UserInfo.getUserId();
        insert rc;
        Transfer__c tc = new Transfer__c();
        tc.booking__c = bk.Id;
        insert tc;
        test.starttest();
        BookingWelcomeMail.sendWelcomeMail(bk.Id,'sdfg');
         //BookingWelcomeMail.sendWelcomeMail2(new List<Booking__c>{bk});
        BookingWelcomeMail.sendLoanChecklistEmail(bk.Id);
         BookingWelcomeMail.sendAssignmentAgreementRequest(bk.Id);
         BookingWelcomeMail.getTransferRecordDetails(bk.Id);
        BookingWelcomeMail.createBookingRecordDetails(bk.Id, 'Test ld', '9988776655', 'India', userinfo.getuseremail(), 'ABCTY1234D');
         BookingWelcomeMail.sendEmailToCustomer(bk.Id,'BookingForm');
        BookingWelcomeMail.sendEmailToCustomer(bk.Id,'NDC');
        BookingWelcomeMail.sendEmailToCustomer(bk.Id,'PC');
        BookingWelcomeMail.testingMethod();
        
        //BookingWelcomeMail.sendEmailToCustomer2(bk.Id,'BookingForm');
        //BookingWelcomeMail.sendEmailToCustomer2(bk.Id,'NDC');
        //BookingWelcomeMail.sendEmailToCustomer2(bk.Id,'PC');
        
        test.stoptest();
    }

}