force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SBI</fullName>
            </value>
            <value>
                <fullName>Navi</fullName>
            </value>
            <value>
                <fullName>HDFC</fullName>
            </value>
            <value>
                <fullName>Tata Capital</fullName>
            </value>
            <value>
                <fullName>IIFL</fullName>
            </value>
            <value>
                <fullName>LT</fullName>
                <label>L&amp;T</label>
            </value>
            <value>
                <fullName>Union Bank</fullName>
            </value>
            <value>
                <fullName>Canara</fullName>
            </value>
            <value>
                <fullName>Shriram</fullName>
            </value>
            <value>
                <fullName>PNB</fullName>
            </value>
            <value>
                <fullName>Bajaj</fullName>
            </value>
            <value>
                <fullName>ICICI</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Piramal</fullName>
            </value>
            <value>
                <fullName>Allahabad Bank</fullName>
            </value>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Anand Rathi</fullName>
            </value>
            <value>
                <fullName>Axis</fullName>
            </value>
            <value>
                <fullName>Godrej</fullName>
            </value>
            <value>
                <fullName>BOI</fullName>
            </value>
            <value>
                <fullName>Karnataka Bank</fullName>
            </value>
            <value>
                <fullName>Central bank</fullName>
            </value>
            <value>
                <fullName>Yes Bank</fullName>
            </value>
            <value>
                <fullName>Bank Of Maharashtra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Finance_User__c.field-meta.xml
<CustomField>
    <fullName>Finance_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Mode_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_Of_Payment__c</fullName>
    <label>Mode Of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>HomeLoan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>Total_Cost_Ex_Leg_Main__c  - Total_received_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount__c</fullName>
    <formula>Total_received_Amount__c -  Refunded_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Received Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <formula>IF(Quote__c != null,TEXT(Quote__r.Project__c),IF(Booking__c !=null,TEXT(Booking__r.Project__c),&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <externalId>true</externalId>
    <label>S No</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>Rc-{000}</displayFormat>
        <label>Receipt  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Mode_of_payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_payment__c</fullName>
    <label>Mode of payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>RTGS</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <label>Check</label>
            </value>
            <value>
                <fullName>NEFT</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>IMPS</fullName>
            </value>
            <value>
                <fullName>RTGS/IMPS/NEFT</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Received_Bank__c.field-meta.xml
<CustomField>
    <fullName>Payment_Received_Bank__c</fullName>
    <label>Payment Received Bank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HDFC</fullName>
            </value>
            <value>
                <fullName>Bank Of India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/Receipt_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Receipt Line Item</label>
    <nameField>
        <label>Receipt Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Approval_Status1__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status1__c</fullName>
    <label>Approval Status Actual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <formula>ISPICKVAL(Receipt__r.Approval_status__c, &apos;Approved&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approval Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipt Line Items</relationshipLabel>
    <relationshipName>Receipt_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>RTGS</fullName>
            </value>
            <value>
                <fullName>cheque</fullName>
            </value>
            <value>
                <fullName>NEFT</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>IMPS</fullName>
            </value>
            <value>
                <fullName>RTGS/IMPS/NEFT</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Payment_From__c.field-meta.xml
<CustomField>
    <fullName>Payment_From__c</fullName>
    <label>Payment From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Payment_schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_schedule__c</fullName>
    <label>Payment schedule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Payment_schedule__c.Booking__c</field>
            <operation>equals</operation>
            <valueField>$Source.Booking__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payment_schedule__c</referenceTo>
    <relationshipLabel>Receipt Line Items</relationshipLabel>
    <relationshipName>Receipt_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Schedules</fullName>
            </value>
            <value>
                <fullName>Additional</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Receipt Line Items</relationshipLabel>
    <relationshipName>Receipt_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RecreatingReceiptDate.cls
public without sharing class RecreatingReceiptDate {

    @AuraEnabled
    public static void recreateReceipts(Id bookingId) {
        markReceiptLineItemsRejected(bookingId);
        recreateReceiptLineItems(bookingId);
        callTheMethodOfReceiptDate(bookingId);
    }
    
    private static void markReceiptLineItemsRejected(Id bookingId) {
        try {
            List<Receipt_Line_Item__c> lineItems = [
                SELECT Id, Approval_Status1__c, Description__c
                FROM Receipt_Line_Item__c
                WHERE Receipt__r.Booking__c = :bookingId and Approval_Status1__c = 'Approved'
            ];
            
            for (Receipt_Line_Item__c item : lineItems) {
                item.Approval_Status1__c = 'Rejected';
                item.Description__c = 'Made by system';
            }
            
            if (!lineItems.isEmpty()) {
                update lineItems;
            }
        } catch (Exception e) {
            System.debug('Error updating line items: ' + e.getMessage());
            throw new AuraHandledException('Failed to reject receipts: ' + e.getMessage());
        }
    }
    
  
    private static void recreateReceiptLineItems(Id bookingId) {
        try {
            List<Receipt__c> receipts = [
                SELECT Id, Name, Receipt_Name__c, Remarks__c, Finance_User__c, 
                       Receipt_date__c, Payment_From__c, Check_Transaction_Nmber__c,
                       Amount_received__c, Mode_of_payment__c, Bank__c,
                       Approval_status__c,(select Id,Name,Bank_Name__c,Payment_From__c,Mode_of_Payment__c,Cheque_no_Transaction_Number__c 
                       from Receipt_Line_Items__r)
                FROM Receipt__c 
                WHERE Booking__c = :bookingId and Approval_status__c = 'Approved'
                ORDER BY Receipt_Date__c ASC NULLS FIRST
            ];
            
            Booking__c bk = [SELECT Id, Name, Finance_User__c, Project__c FROM Booking__c WHERE Id = :bookingId LIMIT 1];
            
            for (Receipt__c rc : receipts) {
                // Skip receipts that have no line items — nothing to copy from
                if (rc.Receipt_Line_Items__r == null || rc.Receipt_Line_Items__r.isEmpty()) {
                    continue;
                }

                Receipt_Line_Item__c firstItem = rc.Receipt_Line_Items__r[0];

                Receipt_Line_Item__c dummyLineItem = new Receipt_Line_Item__c(
                    Bank_Name__c = firstItem.Bank_Name__c,
                    Payment_From__c = firstItem.Payment_From__c,
                    Mode_of_Payment__c = firstItem.Mode_of_payment__c,
                    Cheque_no_Transaction_Number__c = firstItem.Cheque_no_Transaction_Number__c
                );
                
                List<Receipt_Line_Item__c> polist = new List<Receipt_Line_Item__c>{dummyLineItem};
                String PaymentFrom = rc.Payment_From__c;
                String pon = rc.Receipt_Name__c;
                String remark = rc.Remarks__c;
                String poc = rc.Receipt_date__c != null ? String.valueOf(rc.Receipt_date__c) : String.valueOf(Date.today());
                Decimal paidAmount = rc.Amount_received__c;
                Boolean isFromRefactor = true;
                
                insertReceiptLineItems(rc.Id,polist, PaymentFrom, pon, remark, poc, bk, paidAmount, isFromRefactor);
            }
        } catch (Exception e) {
            System.debug('Error recreating receipt line items: ' + e.getMessage());
            throw new AuraHandledException('Failed to recreate receipts: ' + e.getMessage());
        }
    }
    
    private static void callTheMethodOfReceiptDate(Id bookingId) {
        try {
            List<Payment_Schedule__c> payList = [
                SELECT Id, Name, Last_Payment_Date__c, 
                (SELECT Id, Name, Receipt__r.Receipt_Date__c 
                 FROM Receipt_Line_Items__r where Approval_Status1__c != 'Rejected'
                 ORDER BY Receipt__r.Receipt_Date__c DESC 
                 LIMIT 1) 
                FROM Payment_Schedule__c 
                WHERE Booking__c = :bookingId
            ];
            
            List<Payment_Schedule__c> schedulesToUpdate = new List<Payment_Schedule__c>();
            
            for(Payment_Schedule__c pay : payList) {
                if(!pay.Receipt_Line_Items__r.isEmpty()) {
                    pay.Last_Payment_Date__c = pay.Receipt_Line_Items__r[0].Receipt__r.Receipt_Date__c;
                    schedulesToUpdate.add(pay);
                }
            }
            
            if(!schedulesToUpdate.isEmpty()) {
                update schedulesToUpdate;
            }
        } catch (Exception e) {
            System.debug('Error updating last payment dates: ' + e.getMessage());
            throw new AuraHandledException('Failed to update last payment dates: ' + e.getMessage());
        }
    }
    
    @AuraEnabled
    public static String insertReceiptLineItems(Id repId,List<Receipt_Line_Item__c> polist, string PaymentFrom, string pon, string remark, string poc, Booking__c bk, Decimal paidAmount, boolean isFromRefactor) {
        
        //List<Receipt__c> dupRcpList = [Select Id,Name from Receipt__c where Check_Transaction_Nmber__c =:polist[0].Cheque_no_Transaction_Number__c ];
        
            Receipt__c rc = new Receipt__c();
            rc.Receipt_Name__c=pon;
            rc.Remarks__c = remark;
            rc.Finance_User__c = bk.Finance_User__c;
            rc.Receipt_date__c=date.valueof(poc);
            rc.Payment_From__c = PaymentFrom;
            rc.Check_Transaction_Nmber__c = polist[0].Cheque_no_Transaction_Number__c;
            rc.Amount_received__c = paidAmount;
            rc.Mode_of_payment__c = polist[0].Mode_of_Payment__c;
            rc.Payment_Received_Bank__c = polist[0].Bank_Name__c;
            //rc.Cheque_Date__c = polist[0].Cheque_Date__c;
            rc.Booking__c=bk.Id;
            if(isFromRefactor == true){
                rc.Approval_status__c='Approved by Finance Team';
            }
            //rc.Interest_Paid_Amount__c = interestAmount;
            //insert rc;
            
            List<Receipt_Line_Item__c> receiptsToCreate = new List<Receipt_Line_Item__c>();
            List<Payment_Schedule__c> payList = [SELECT Id, Amount__c, Project_Name__c, Pending_Amount__c, S_No__c FROM Payment_Schedule__c WHERE Booking__c =: bk.Id ORDER BY is_Demanded__c desc, Payment_Due_Date__c ASC nulls first, S_No__c asc];
            List<Payment_Schedule__c> newpayList = new List<Payment_Schedule__c>();
            List<Payment_Schedule__c> orderedPayList = new List<Payment_Schedule__c>();
            Set<Id> payIds = new Set<Id>();

            // --- Life On the Green: separate payment-schedule sequence ---
            if (!payList.isEmpty() && payList[0].Project_Name__c == 'Life On the Green' && payList.size() >= 4) {
                orderedPayList.add(payList[0]); // 1
                orderedPayList.add(payList[1]); // 2
                orderedPayList.add(payList[3]); // 4
                orderedPayList.add(payList[2]); // 3
                for (Integer i = 4; i < payList.size(); i++) {
                    orderedPayList.add(payList[i]); // 5, 6, 7...
                }
            } else {
                // Default order for all other projects — existing behavior unchanged
                orderedPayList = payList;
            }
         
                if(paidAmount > 0){
                    for (Payment_Schedule__c paymentSchedule : orderedPayList) {
                        
                        if (paidAmount <= 0 || paidAmount == null) {
                            break;
                        }
                        
                        if (paymentSchedule.Pending_Amount__c != null && paymentSchedule.Pending_Amount__c > 0) {
                            
                            Decimal amountToReceive = Math.min(paymentSchedule.Pending_Amount__c, paidAmount);
                            paidAmount -= amountToReceive;
                            
                            Receipt_Line_Item__c rece = new Receipt_Line_Item__c();
                            rece.Booking__c = bk.Id;
                            rece.Name = 'Against Payment Schedule';
                            rece.Payment_Type__c = 'Payment Schedules';
                            rece.Receipt__c = repId;
                            rece.Payment_Schedule__c = paymentSchedule.Id;
                            rece.Received_Amount__c = amountToReceive;
                            rece.Amount__c = amountToReceive;
                            rece.Bank_Name__c = polist[0].Bank_Name__c;
                            rece.Approval_Status1__c = 'Approved';
                            rece.Payment_From__c = polist[0].Payment_From__c;
                            rece.Mode_of_Payment__c =  polist[0].Mode_of_Payment__c;
                            rece.Cheque_no_Transaction_Number__c = polist[0].Cheque_no_Transaction_Number__c;
                            receiptsToCreate.add(rece);
                            payIds.add(paymentSchedule.Id);
                        }
                        
                    }
                }
                
            
            if(paidAmount !=null && paidAmount > 0)
            {
                Integer PaymentScheduleSize = payList.size();
                Receipt_Line_Item__c rece = new Receipt_Line_Item__c();
                rece.Booking__c = bk.Id;
                rece.Name = 'Against Payment Schedule';
                rece.Payment_Type__c = 'Payment Schedules';
                rece.Receipt__c = repId;
                rece.Payment_Schedule__c = payList[PaymentScheduleSize-1].Id;
                rece.Received_Amount__c = paidAmount;
                rece.Amount__c = paidAmount;
                rece.Approval_Status1__c = 'Approved';
                rece.Bank_Name__c = polist[0].Bank_Name__c;
                rece.Payment_From__c = polist[0].Payment_From__c;
                rece.Mode_of_Payment__c =  polist[0].Mode_of_Payment__c;
                rece.Cheque_no_Transaction_Number__c = polist[0].Cheque_no_Transaction_Number__c;
                receiptsToCreate.add(rece);
            }
            
           
            if (!receiptsToCreate.isEmpty()) {
                upsert receiptsToCreate;
            }
            
           
            return rc.Id;
        
    }
    
    public static void testCoverage(){
        Integer i=0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}