force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Block_Number__c.field-meta.xml
<CustomField>
    <fullName>Block_Number__c</fullName>
    <formula>Plot__r.Block1__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Block Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <formula>TEXT( SLead__r.Lead_source__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Mobile_Primary1__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Primary1__c</fullName>
    <label>Mobile Primary</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Mobile_Primary2__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Primary2__c</fullName>
    <label>Mobile Primary</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Booking Approved</fullName>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Agreement Under Process</fullName>
            </value>
            <value>
                <fullName>First Disbursement Under Process</fullName>
            </value>
            <value>
                <fullName>Progressive Collections</fullName>
                <label>Progressive Milestones</label>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Handover</fullName>
            </value>
            <value>
                <fullName>Handed Over</fullName>
            </value>
            <value>
                <fullName>Swapping In Progress</fullName>
            </value>
            <value>
                <fullName>Swapping Completed</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Assignment Progress</fullName>
            </value>
            <value>
                <fullName>Assignment Completed</fullName>
            </value>
            <value>
                <fullName>Agreement</fullName>
                <isActive>false</isActive>
                <label>Agreement</label>
            </value>
            <value>
                <fullName>Booking</fullName>
                <isActive>false</isActive>
                <label>Booking</label>
            </value>
            <value>
                <fullName>D&amp;P</fullName>
                <isActive>false</isActive>
                <label>D&amp;P</label>
            </value>
            <value>
                <fullName>Legal Finalization</fullName>
                <isActive>false</isActive>
                <label>Legal Finalization</label>
            </value>
            <value>
                <fullName>Loan Approval</fullName>
                <isActive>false</isActive>
                <label>Loan Approval</label>
            </value>
            <value>
                <fullName>Maintanance</fullName>
                <isActive>false</isActive>
                <label>Maintanance</label>
            </value>
            <value>
                <fullName>Possession</fullName>
                <isActive>false</isActive>
                <label>Possession</label>
            </value>
            <value>
                <fullName>Swapping</fullName>
                <isActive>false</isActive>
                <label>Swapping</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Welcome call</fullName>
            </value>
            <value>
                <fullName>Legal Process</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Closed won</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
                <isActive>false</isActive>
                <label>Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit_NumberFor__c.field-meta.xml
<CustomField>
    <fullName>Unit_NumberFor__c</fullName>
    <formula>Plot__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Detail__c/Call_Detail__c.object-meta.xml
<CustomObject>
    <label>Call Detail</label>
    <nameField>
        <displayFormat>CD{00000000}</displayFormat>
        <label>Call Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Detail__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <formula>TEXT(Lead__r.Lead_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ANSWER</fullName>
            </value>
            <value>
                <fullName>CONNECTING</fullName>
            </value>
            <value>
                <fullName>Connected</fullName>
            </value>
            <value>
                <fullName>Customer Busy</fullName>
            </value>
            <value>
                <fullName>Originate</fullName>
            </value>
            <value>
                <fullName>Call Complete</fullName>
            </value>
            <value>
                <fullName>BUSY</fullName>
            </value>
            <value>
                <fullName>CANCEL</fullName>
            </value>
            <value>
                <fullName>Called Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Follow_up__c/Follow_up__c.object-meta.xml
<CustomObject>
    <label>Follow up</label>
    <nameField>
        <displayFormat>F-{000}</displayFormat>
        <label>Follow up Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_up__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <label>Feedback</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZLead</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Follow ups</relationshipLabel>
    <relationshipName>Follow_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <formula>SLead__r.Lead_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/lead__c/lead__c.object-meta.xml
<CustomObject>
    <label>clead</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>cleads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/lead__c/fields/Last_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_Date__c</fullName>
    <formula>DATEVALUE(LastModifiedDate)</formula>
    <label>Last Modified Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/lead__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <displayFormat>Ld-{000}</displayFormat>
    <label>Lead ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/lead__c/fields/Lead_status__c.field-meta.xml
<CustomField>
    <fullName>Lead_status__c</fullName>
    <label>Lead status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Qualifed</fullName>
            </value>
            <value>
                <fullName>SV Schedule</fullName>
            </value>
            <value>
                <fullName>Unqualifed</fullName>
            </value>
            <value>
                <fullName>SV Done</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SiteVisit-{0000}</displayFormat>
        <label>Site Visits Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Canceled_Reason__c.field-meta.xml
<CustomField>
    <fullName>Canceled_Reason__c</fullName>
    <label>Canceled Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Scheduled Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Reschedule_Date__c.field-meta.xml
<CustomField>
    <fullName>Reschedule_Date__c</fullName>
    <label>Reschedule Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HomeNotificationController.cls
public with sharing class HomeNotificationController {
    
    @AuraEnabled
    public static datawrapperfl getFollowUpInformation(Integer pageNumber,Integer pageSize)
    {
        datawrapperfl dwfl = new datawrapperfl();
        Integer offset = (pageNumber - 1)  * pageSize;
        Id currentUserId = UserInfo.getUserId();
        list<Follow_Up__c>followUpDetails = New list<Follow_Up__c>();
        Boolean isAdmin = [SELECT Profile.Name FROM User WHERE Id = :currentUserId].Profile.Name == 'System Administrator';
        system.debug(isAdmin);
        system.debug(pageNumber);
        system.debug(pageSize);
        system.debug(offset);
        List<Follow_Up__c> allCount = [Select Id,Name,Scheduled_Date__c,Status__c,Owner.Name,SLead__c,SLead__r.Name,SLead__r.Status,SLead__r.Last_Comment__c,SLead__r.Id,SLead__r.Lead_Age__c from Follow_Up__c  where Status__c='Scheduled' AND Scheduled_Date__c=today ];
        
        followUpDetails = [Select Id,Name,Scheduled_Date__c,Status__c,Owner.Name,SLead__c,SLead__r.Name,SLead__r.Status,SLead__r.Last_Comment__c,SLead__r.Id,SLead__r.Lead_Age__c from Follow_Up__c  where Status__c='Scheduled' AND Scheduled_Date__c=today order by Scheduled_Date__c
                           LIMIT :pageSize OFFSET :offset];
        
        dwfl.FollowupldList = followUpDetails;
        dwfl.FollowupCount = allCount.size();
        
        return dwfl;
    }
    public class datawrapperfl{
        @AuraEnabled
        public Decimal FollowupCount {get; set;}
        @AuraEnabled
        public List<Follow_Up__c> FollowupldList {get; set;}
    }
    @auraEnabled
    public static datawrappersv getSiteVistInformation(Integer pageNumber,Integer pageSize)
    {
        datawrappersv dwsv = new datawrappersv();
        Integer offset = (pageNumber - 1) * pageSize;
        Id currentUserId = UserInfo.getUserId();
        list<Site_Visit__c>svDetails = New list<Site_Visit__c>();
        Boolean isAdmin = [SELECT Profile.Name FROM User WHERE Id = :currentUserId].Profile.Name == 'System Administrator';
        List<Site_Visit__c> allCount =[Select Id,Name,SLead__c,Date__c,Status__c,Owner.Name,SLead__r.Name,SLead__r.Status,SLead__r.Last_Comment__c,SLead__r.Id,Canceled_Reason__c,SLead__r.Description,SLead__r.Lead_Age__c from Site_Visit__c  where (Status__c='Scheduled' OR Status__c='Reschedule' ) AND Date__c=today];
        svDetails=[Select Id,Name,SLead__c,Date__c,Status__c,Owner.Name,SLead__r.Name,SLead__r.Status,SLead__r.Last_Comment__c,SLead__r.Id,Canceled_Reason__c,SLead__r.Description,SLead__r.Lead_Age__c from Site_Visit__c  where (Status__c='Scheduled' OR Status__c='Reschedule' ) AND Date__c=today order by Date__c  LIMIT :pageSize OFFSET :offset];
        dwsv.SiteVisitldList = svDetails;
        dwsv.Noofsitevisits = allCount.size();
        
        return dwsv;
    }
    public class datawrappersv{
        @AuraEnabled
        public Decimal Noofsitevisits {get; set;}
        @AuraEnabled
        public List<Site_Visit__c> SiteVisitldList {get; set;}
    }
    @auraEnabled
    public static list<Follow_Up__c> getPendingFollowUpInformation()
    {
        List<Follow_Up__c> followUpDetails=[Select Id,Name,Scheduled_Date__c,Status__c,Owner.Name,SLead__c,SLead__r.Last_Comment__c,SLead__r.Name,SLead__r.Status,SLead__r.Id,SLead__r.Lead_Age__c from Follow_Up__c  where (Status__c='Scheduled') AND Scheduled_Date__c < today order by Scheduled_Date__c  ];
        System.debug(followUpDetails);
        return followUpDetails;
    }
    @auraEnabled
    public static datawrapper2 getReassignedLeads(Integer pageSize, Integer pageNumber)
    {
        
        
        
        Date today = Date.today();
        
        // Query LeadHistory for changes to the OwnerId field that happened today
        List<LeadHistory> leadHistoryList = [SELECT LeadId 
                                             FROM LeadHistory 
                                             WHERE Field = 'Owner' 
                                             AND CreatedDate = TODAY];
        
        // Extract LeadIds from the history records
        Set<Id> leadIds = new Set<Id>();
        for (LeadHistory history : leadHistoryList) {
            leadIds.add(history.LeadId);
        }
        
        // Query the Lead records using the extracted LeadIds and filter by current owner and CreatedDate
        
        datawrapper2 dw2 = new datawrapper2();
        date dt = system.today() -7;
        Integer offset = (pageNumber - 1) * pageSize;
        Id currentUserId = UserInfo.getUserId();
        List<Lead> lstld= new  List<Lead>();
        List<Lead> lstldnewLead= new  List<Lead>();
        List<Lead> totalld= new  List<Lead>();
        Boolean isAdmin = [SELECT Profile.Name FROM User WHERE Id = :currentUserId].Profile.Name == 'System Administrator';
        lstld = [SELECT Id, Name, OwnerId, CreatedDate,Allocated_Project__c,Phone__c,(select id,name from Call_Details__r where createddate = today) FROM Lead WHERE Id IN :leadIds  AND CreatedDate < TODAY
                 ORDER BY CreatedDate DESC 
                 LIMIT :pageSize OFFSET :offset];
        for(Lead ld : lstld){
            if(ld.Call_Details__r.size() == 0){
                lstldnewLead.add(ld);
            }
        }
        dw2.noActivityldList = lstldnewLead;
        totalld = [SELECT Id, Name, OwnerId,Allocated_Project__c,Phone__c, CreatedDate FROM Lead WHERE Id IN :leadIds AND CreatedDate < TODAY
                   ORDER BY CreatedDate DESC];    
        dw2.noActivityCount = totalld.size();
        
        return dw2;
    }
    @auraEnabled
    public static list<Site_Visit__c> getPendingSiteVistInformation()
    {
        System.debug('Sv Details');
        List<Site_Visit__c> svDetails=[Select Id,Name,SLead__c,Date__c,Status__c,Owner.Name,SLead__r.Last_Comment__c,SLead__r.Name,SLead__r.Status,SLead__r.Id,Canceled_Reason__c,SLead__r.Description,SLead__r.Lead_Age__c from Site_Visit__c  where (Status__c='Scheduled' OR Status__c='Reschedule') AND Date__c < today order by Date__c ];
        return svDetails;
    }
    /* @auraEnabled
public static list<Task> getMissedCallTask()
{
List<Task> taskDetails=[select  id,subject,TaskSubtype,Status,Owner.Name,whoid,who.Name from task where subject='Missed Call' AND TaskSubtype='Task' AND Status='Open' AND whoid!=null AND ownerId=:userinfo.getUserId()];
System.debug(taskDetails);
return taskDetails;
}*/
    
    @auraEnabled
    public static list<Call_Detail__c> getMissedCallTask()
    {
         Id currentUserId = UserInfo.getUserId();
        List<Call_Detail__c> taskDetails=[select  id,Lead__c,Lead__r.Name,Lead__r.Lead_Status__c,Lead__r.OwnerId,Owner.Name from Call_Detail__c where createddate=today  and Status__c = 'Missed' and Lead__r.OwnerId =: currentUserId and Lead__c != null];
        System.debug(taskDetails);
        return taskDetails;
    }
    
    @auraEnabled
    public static String updateSvDetils(String recID,String svStatus,String updateValue,String conducatedDate)
    {
        System.debug(conducatedDate);
        list<Site_Visit__c> svData=[select Id,Name,SLead__c,Status__c,Feedback__c,Date__c,Canceled_Reason__c from Site_Visit__c where id=:recID];
        if(svData.size()>0)
        {
            svData[0].Status__c=svStatus;
            if(svStatus=='Cancelled')
                svData[0].Canceled_Reason__c=updateValue;
            else if(svStatus=='Completed') {	 
                if(conducatedDate!=null && conducatedDate!=''){
                    String formattedFollowUpDate = followUpController.dateFormat(conducatedDate);
                    svData[0].Date__c=datetime.valueOf(formattedFollowUpDate);
                }
                svData[0].Feedback__c=updateValue;
            } 
            else if(svStatus=='Rescheduled')
            {
                String formattedFollowUpDate = followUpController.dateFormat(updateValue);
                svData[0].Reschedule_Date__c = datetime.valueOf(formattedFollowUpDate);
            } 
            update  svData[0];
            return 'Updated';
        }
        return null;
    }
    
    @auraEnabled
    public static String updateFollowupDetails(String recID, String FLStatus, String comments) {
        List<Follow_Up__c> svData = [SELECT Id, Status__c,Feedback__c FROM Follow_Up__c WHERE Id = :recID LIMIT 1];
        if (!svData.isEmpty()) {
            svData[0].Status__c = FLStatus;
            svData[0].Feedback__c = comments;
            update svData[0];
            return 'Updated';
        } 
        else {
            return 'Record not found';
        }
    }
    
    @AuraEnabled
    public static datawrapper todaysLeads(Integer pageSize, Integer pageNumber){
        datawrapper dw = new datawrapper();
        Integer offset = (pageNumber - 1) * pageSize;
        Id currentUserId = UserInfo.getUserId();
        List<Lead> lstld;
        Boolean isAdmin = [SELECT Profile.Name FROM User WHERE Id = :currentUserId].Profile.Name == 'System Administrator';
        lstld = [SELECT id,Name,Lead_Type__c,Lead_ID__c,Status,Lead_source__c,Lead_Age__c,Allocated_Project__c,Email__c,Secondary_Email__c,Phone__c,Secondary_Phone__c,Last_Modified_Date__c,createddate,(select id from call_details__r) 
                 FROM Lead 
                 WHERE createddate = TODAY 
                 ORDER BY CreatedDate DESC 
                 LIMIT :pageSize OFFSET :offset];
        
        List<Lead> lstld1 =[select id,Name,Lead_Type__c,Lead_ID__c,Lead_Age__c,Status,Lead_source__c,Allocated_Project__c,Email__c,Secondary_Email__c,Phone__c,Secondary_Phone__c,Last_Modified_Date__c,createddate from Lead where createddate=today];
        List<Lead> lstld2 =[select id,Name,Lead_Type__c,Lead_ID__c,Lead_Age__c,Status,Lead_source__c,Allocated_Project__c,Email__c,Secondary_Email__c,Phone__c,Secondary_Phone__c,Last_Modified_Date__c,createddate from Lead where createddate=today And Lead_Type__c='Re-Engaged'];
        dw.ldListtodays = lstld;
        dw.todaysldCount = lstld1.size();
        dw.ldreengagedleads = lstld2.size();
        return dw;
    }
    
    public class datawrapper{
        @AuraEnabled
        public Decimal todaysldCount {get; set;}
        @AuraEnabled
        public List<Lead> ldListtodays {get; set;}
        @AuraEnabled
        public Decimal ldreengagedleads {get; set;}
    }
    
    public class datawrapper2{
        @AuraEnabled
        public Decimal noActivityCount {get; set;}
        @AuraEnabled
        public List<Lead> noActivityldList {get; set;}
    }
    @AuraEnabled
    public static String getUserName() {
        String userId = UserInfo.getUserId();
        User currentUser = [SELECT Name FROM User WHERE Id = :userId];
        return currentUser.Name;
    }
    @AuraEnabled
    public static datawrapper2 getnoactivityleads(Integer pageSize, Integer pageNumber) {
        datawrapper2 dw2 = new datawrapper2();
        date dt = system.today() -7;
        Integer offset = (pageNumber - 1) * pageSize;
        Id currentUserId = UserInfo.getUserId();
        List<Lead> lstld= new  List<Lead>();
        List<Lead> totalld= new  List<Lead>();
        Boolean isAdmin = [SELECT Profile.Name FROM User WHERE Id = :currentUserId].Profile.Name == 'System Administrator';
        lstld = [select Id, Name,Lead_ID__c,Allocated_Project__c,Phone__c from Lead where Lead_Status__c != 'Unqualifed' AND Lead_Status__c != 'Closed Lost' AND Lead_Status__c != 'Booked' AND LastmodifiedDate < :dt AND (Id NOT IN (select SLead__c from Site_visit__c where LastmodifiedDate >=:dt)) AND (Id NOT IN (select SLead__c from Follow_up__c where LastmodifiedDate >=:dt))
                 ORDER BY CreatedDate DESC 
                 LIMIT :pageSize OFFSET :offset];
        dw2.noActivityldList = lstld;
        totalld = [select Id, Name,Lead_ID__c,Allocated_Project__c,Phone__c from Lead where Lead_Status__c != 'Unqualifed' AND Lead_Status__c != 'Closed Lost' AND Lead_Status__c != 'Booked' AND LastmodifiedDate < :dt AND (Id NOT IN (select SLead__c from Site_visit__c where LastmodifiedDate >=:dt)) AND (Id NOT IN (select SLead__c from Follow_up__c where LastmodifiedDate >=:dt))
                   ORDER BY CreatedDate DESC];    
        dw2.noActivityCount = totalld.size();
        
        return dw2;
    }
    
    @AuraEnabled
    public static datawrapper2 getNoFollowUpLeads(Integer pageSize, Integer pageNumber){
        
        datawrapper2 dw2 = new datawrapper2();
        date dt = system.today() -7;
        Integer offset = (pageNumber - 1) * pageSize;
        Id currentUserId = UserInfo.getUserId();
        List<Lead> lstld= new  List<Lead>();
        List<Lead> totalld= new  List<Lead>();
        Boolean isAdmin = [SELECT Profile.Name FROM User WHERE Id = :currentUserId].Profile.Name == 'System Administrator';
        lstld = [SELECT Id, Name,Lead_ID__c,Allocated_Project__c,Phone__c FROM Lead WHERE Id NOT IN (SELECT SLead__c FROM Follow_Up__c) AND Lead_Status__c != 'Unqualifed' AND Lead_Status__c != 'Closed Lost' AND Lead_Status__c != 'Booked'
                 ORDER BY CreatedDate DESC 
                 LIMIT :pageSize OFFSET :offset];
        dw2.noActivityldList = lstld;
        totalld = [SELECT Id, Name,Lead_ID__c,Allocated_Project__c,Phone__c FROM Lead WHERE Id NOT IN (SELECT SLead__c FROM Follow_Up__c) AND Lead_Status__c != 'Unqualifed' AND Lead_Status__c != 'Closed Lost' AND Lead_Status__c != 'Booked'
                   ORDER BY CreatedDate DESC];    
        dw2.noActivityCount = totalld.size();
        
        return dw2;
        
        
        
    }
    
    @AuraEnabled
    public static datawrapper4 todaysBookings(Integer pageSize, Integer pageNumber){
        datawrapper4 dw4 = new datawrapper4();
        Integer offset = (pageNumber - 1) * pageSize;
        Id currentUserId = UserInfo.getUserId();
        List<Booking__c> lstbook;
        Boolean isAdmin = [SELECT Profile.Name FROM User WHERE Id = :currentUserId].Profile.Name == 'System Administrator';
        lstbook = [SELECT id,Name,Project__c,Unit_NumberFor__c,Stage__c,Contact_Telephone_Number__c,Block_Number__c,Contact_Telephone_Number1__c,Mobile__c,Mobile_Primary1__c,Mobile_Primary2__c,createddate 
                   FROM Booking__c 
                   WHERE createddate = TODAY 
                   ORDER BY CreatedDate DESC 
                   LIMIT :pageSize OFFSET :offset];
        dw4.ldListbooking = lstbook;
        dw4.Noofbooking = lstbook.size();
        return dw4;
    }
    
    public class datawrapper4{
        @AuraEnabled
        public List<Booking__c> ldListbooking {get; set;}
        @AuraEnabled
        public integer Noofbooking {get; set;}
        
    }
    
}