force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Email1__c.field-meta.xml
<CustomField>
    <fullName>Email1__c</fullName>
    <defaultValue>&apos;Helpdesk.kar@sowparnika.com&apos;</defaultValue>
    <label>Mail CC User</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Flat_Unit__c.field-meta.xml
<CustomField>
    <fullName>Flat_Unit__c</fullName>
    <formula>IF(Property_TypeFor__c == &apos;Villa&apos;,&apos;Villa&apos;,&apos;Flat&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Flat/Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/lead1__c.field-meta.xml
<CustomField>
    <fullName>lead1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZLead</label>
    <referenceTo>lead__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Owner_Designation__c.field-meta.xml
<CustomField>
    <fullName>Owner_Designation__c</fullName>
    <formula>Owner:User.Designation__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Designation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Owner_NameFor__c.field-meta.xml
<CustomField>
    <fullName>Owner_NameFor__c</fullName>
    <formula>Owner:User.FirstName +&apos; &apos;+ Owner:User.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Secondary_Welcome_Mail__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Welcome_Mail__c</fullName>
    <label>Secondary Welcome Mail</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_received_Amount__c</fullName>
    <label>Total Receipt Amount</label>
    <summarizedField>Receipt__c.Total_Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt__c.Approval_status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit_NumberFor__c.field-meta.xml
<CustomField>
    <fullName>Unit_NumberFor__c</fullName>
    <formula>Plot__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/Co_Applicant__c.object-meta.xml
<CustomObject>
    <label>Co Applicant</label>
    <nameField>
        <label>Co Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Co Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Applicant__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Co Applicants</relationshipLabel>
    <relationshipName>Co_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/lead__c/lead__c.object-meta.xml
<CustomObject>
    <label>clead</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>cleads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Legal_URL__c.field-meta.xml
<CustomField>
    <fullName>Project_Legal_URL__c</fullName>
    <label>Project Legal URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>Rc-{000}</displayFormat>
        <label>Receipt  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Total_Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Received_Amount__c</fullName>
    <label>Total Received Amount</label>
    <summarizedField>Receipt_Line_Item__c.Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Approval_Status1__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt_Line_Item__c.Receipt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/BookingSecondaryWelcomeMail.cls
public class BookingSecondaryWelcomeMail {
    
    
    @AuraEnabled
    public static Booking__c getRecordDetails(String recordId){
        Booking__c bk = [select id,name,First_Applicant_Name__c,Project__c,Booking_Amount__c,Unit_NumberFor__c,Owner_NameFor__c,Owner_Phone__c,Owner_Designation__c from Booking__c where Id=:recordId];
        return bk;
    }
    
    @AuraEnabled
    public static void sendSecondaryWelcomeMail(String recordId, String emailContent){
        string recId = recordId;
        Booking__c l = [SELECT Id,Name,Booking_Amount__c,Flat_Unit__c,Plot__r.Name,Owner.email,Email__c,Email1__c,lead1__r.Email__c,Project__c,Unit_NumberFor__c,Owner.Name,Owner_Designation__c FROM Booking__c where Id=:recordId];
        //Receipt__c rec = [select id,name,Total_Received_Amount__c from Receipt__c where Booking__c =: l.Id and Receipt_Name__c = 'Booking Amount Receipt'];
        List<Co_Applicant__c> coApps = [select id,name,Email__c,Booking__c from Co_Applicant__c where Booking__c =: l.Id];
        Project__c pro = [select id,name,Project_Legal_URL__c,(SELECT ContentDocumentId, ContentDocument.Title FROM ContentDocumentLinks) from Project__c where Project__c = :l.Project__c ];
        List<ContentVersion> contentVersions1 = new List<ContentVersion>();
        List<ContentDocumentLink> contentDocumentLinks = new List<ContentDocumentLink>();
        List<String> lstCCEmail = new List<String>();
        List<OrgWideEmailAddress> owea = new List<OrgWideEmailAddress>();
        owea = [SELECT Id, Address, DisplayName FROM 
                OrgWideEmailAddress WHERE Address=:l.Owner.email];
        
        
        if (l.Email__c != null && l.Email__c != '') {
            lstCCEmail = l.Email__c.split(',');
        }
        if (l.Email1__c != null && l.Email1__c != '') {
            lstCCEmail.addAll(l.Email1__c.split(','));
        }
        
        Messaging.SingleEmailMessage semail = new Messaging.SingleEmailMessage();
        List<Messaging.EmailFileAttachment> emailAttachments = new List<Messaging.EmailFileAttachment>();
        //----------------------------------sale agreement draft-------------------------//
        Set<Id> contentDocumentIds = new Set<Id>();
        for (ContentDocumentLink cdl : pro.ContentDocumentLinks) {
            contentDocumentIds.add(cdl.ContentDocumentId);
        }
        
        List<ContentVersion> contentVersions = [SELECT Title, VersionData, FileExtension FROM ContentVersion WHERE ContentDocumentId IN :contentDocumentIds ORDER BY CreatedDate DESC];
        
        for (ContentVersion cv : contentVersions) {
            Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
            // Set the file name with the correct extension
            attachment.setFileName(cv.Title + '.' + cv.FileExtension);
            attachment.setBody(cv.VersionData);
            emailAttachments.add(attachment);
        }
        
        string welcomeSubject = 'Sowparnika '+l.Project__c+' - '+l.Flat_Unit__c+' '+l.Plot__r.Name+' - Booking Secondary Email';
        //--------------------------------------------demandletter------------------//
            PageReference pref2 = Page.Demand_letter;
            pref2.getParameters().put('id', recId);
            pref2.setRedirect(true);
            system.debug(pref2);
            
            Blob b2;
            if (Test.isRunningTest()) {
                b2 = Blob.valueOf('Unit.Test');
            } else {
                b2 = pref2.getContentAsPDF();
            }
            saveAttachmentToFiles(recId, 'Demand.pdf', b2, contentVersions1, contentDocumentLinks);
            Messaging.EmailFileAttachment attach2 = new Messaging.EmailFileAttachment();
            attach2.setFileName('Demand.pdf');
            attach2.setBody(b2);
            emailAttachments.add(attach2);
        
       //---------------------------------------------Receipt---------------------// 
        /*PageReference pref = Page.ReceiptFormat;
        pref.getParameters().put('id', recId);
        pref.setRedirect(true);
        system.debug(pref);
        
        Blob b;
        if (Test.isRunningTest()) {
            b = Blob.valueOf('Unit.Test');
        } else {
            b = pref.getContent();
        }
        Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
        attach.setFileName('Receipt.pdf');
        attach.setBody(b);
        emailAttachments.add(attach);*/
        //------------------------------------allotment letter-----------------------//
        PageReference pref1 = Page.Allotment_Letter;
        pref1.getParameters().put('id', recId);
        pref1.setRedirect(true);
        
        Blob b1;
        if (Test.isRunningTest()) {
            b1 = Blob.valueOf('Unit.Test');
        } else {
            b1 = pref1.getContent();
        }
        Messaging.EmailFileAttachment attach1 = new Messaging.EmailFileAttachment();
        attach1.setFileName('Allotment Letter.pdf');
        attach1.setBody(b1);
        emailAttachments.add(attach1);
        //---------------------------------------customer kyc--------------------------//
        PageReference pref11 = Page.customerKYCInformation;
        pref11.getParameters().put('id', recId);
        pref11.setRedirect(true);
        
        Blob b11;
        if (Test.isRunningTest()) {
            b11 = Blob.valueOf('Unit.Test');
        } else {
            b11 = pref11.getContent();
        }
        Messaging.EmailFileAttachment attach11 = new Messaging.EmailFileAttachment();
        attach11.setFileName('Customer KYC.pdf');
        attach11.setBody(b11);
        emailAttachments.add(attach11);
        
        semail.setSubject(welcomeSubject);
        List<String> sendTo = new List<String>();
        sendTo.add(l.Email__c);
        if(coApps.size()>0){
            for(Co_Applicant__c ca : coApps){
                if(ca.Email__c != null){
                    sendTo.add(ca.Email__c);
                }
                
            }
        }
        if ( owea.size()>0) {
             lstCCEmail.add(owea[0].Address);
            semail.setOrgWideEmailAddressId(owea[0].Id);
        }
        if(lstCCEmail.size()>0){
            semail.setCcAddresses(lstCCEmail);
        }
        semail.setToAddresses(sendTo);
        //Decimal roudedValue = Math.round(rec.Total_Received_Amount__c);
        String newvalueAmount = l.Booking_Amount__c.setScale(2).format();
        /*semail.setHtmlBody('Dear Sir/Madam,<br/><br/>'+ 
                           'With reference to the welcome E-mail sent to you for the booking done by you, we herewith convey the following:<br/>'+
                           'I. We have received an amount of Rs.'+newvalueAmount+' towards the booking of your Unit No. '+l.Unit_NumberFor__c+'. Request you to kindly transfer the balance amount of 30% of your sale agreement value.'+
                           '<br/> Please find below attachements for further details <br/><br/>Warm regards,<br/>'+
                           l.Owner.Name+'<br/>'+l.Owner_Designation__c+'<br/>Sowparnika');*/
        semail.setPlainTextBody(emailContent);
        if (!emailAttachments.isEmpty()){
            semail.setFileAttachments(emailAttachments);
        }
        if (sendTo.size() > 0){
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{semail});
            system.debug(semail);
        } 
        
        if (!contentVersions1.isEmpty()) {
            insert contentVersions1;
           
        }
        l.Secondary_Welcome_Mail__c = system.now();
        update l;
    }
    private static void saveAttachmentToFiles(Id recId, String fileName, Blob fileBody, List<ContentVersion> contentVersions, List<ContentDocumentLink> contentDocumentLinks) {
        Datetime x =  Datetime.now();
        string userid = UserInfo.getUserId();
        String format = userid.mid(10, 8);
        String EIdFormat = recId+'D'+format+x.year()+x.month()+x.day()+x.millisecond()+'D';
        String title = 'Demand - ' + Date.today().format();
        ContentVersion contentVersion = new ContentVersion();
        contentVersion.Title = title;
        contentVersion.PathOnClient = fileName;
        contentVersion.VersionData = fileBody;
        system.debug('rcirdd saveattch   '+recId);
        contentVersion.FirstPublishLocationId = recId;
        contentVersions.add(contentVersion);
    }

}