force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Welcome call</fullName>
            </value>
            <value>
                <fullName>Legal Process</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Closed won</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
                <isActive>false</isActive>
                <label>Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Payment_Schedule__c/Master_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Master Payment Schedule</label>
    <nameField>
        <label>Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/Master_Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Master_Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Payment Schedule</label>
    <referenceTo>Master_Payment_Schedule__c</referenceTo>
    <relationshipLabel>Payment schedules</relationshipLabel>
    <relationshipName>Payment_schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <externalId>true</externalId>
    <label>S No</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Demanded</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PaymentScheduleMerger1.cls
public class PaymentScheduleMerger1 {

    public static void handleRelatedPaymentSchedules(List<Quote__c> newQuotes) {
        Set<Id> quoteIds = new Set<Id>();
        for (Quote__c quote : newQuotes) {
            quoteIds.add(quote.Id);
        }
system.debug('set of quote Ids  '+quoteIds);
        List<Payment_Schedule__c> relatedPaymentSchedules = [
            SELECT Id,name, Quote__c, payment_percent__c,Master_Payment_Schedule__c,Payment_Due_Date__c,
                   Master_Payment_Schedule__r.Completed_Date__c,Master_Payment_Schedule__r.Status__c
            FROM Payment_Schedule__c
            WHERE Quote__c IN :quoteIds
              AND Master_Payment_Schedule__r.Status__c = 'Completed'
        ];
system.debug('set of relatedPaymentSchedules Ids  '+relatedPaymentSchedules);
        //prepareForMerge(relatedPaymentSchedules);
        if(relatedPaymentSchedules.size() > 0){
            mergePaymentSchedulesAfterInsert(relatedPaymentSchedules);
        }
    }
    
    
    public static void handleRelatedPaymentSchedulesBooking(List<Booking__c> newQuotes) {
        Set<Id> quoteIds = new Set<Id>();
        for (Booking__c quote : newQuotes) {
            quoteIds.add(quote.Id);
        }
system.debug('set of quote Ids  '+quoteIds);
        List<Payment_Schedule__c> relatedPaymentSchedules = [
            SELECT Id,name, Booking__c, payment_percent__c,Master_Payment_Schedule__c,Payment_Due_Date__c,
                   Master_Payment_Schedule__r.Completed_Date__c,Master_Payment_Schedule__r.Status__c
            FROM Payment_Schedule__c
            WHERE Booking__c IN :quoteIds
              AND Master_Payment_Schedule__r.Status__c = 'Completed'
        ];
system.debug('set of relatedPaymentSchedules Ids  '+relatedPaymentSchedules);
        //prepareForMerge(relatedPaymentSchedules);

        mergePaymentSchedulesAfterInsert(relatedPaymentSchedules);
    }

    public static void prepareForMerge(List<Payment_Schedule__c> paymentSchedules) {
       
    }

    public static void mergePaymentSchedulesAfterInsert(List<Payment_Schedule__c> paymentSchedules) {
      	Date dueDate;
        Payment_Schedule__c masterPaymentSchedule = findMasterPaymentSchedule(paymentSchedules);

        Decimal totalPaymentPercent = 0;
        for (Payment_Schedule__c paymentSchedule : paymentSchedules) {
            totalPaymentPercent += paymentSchedule.Payment_Percent__c;
            dueDate = paymentSchedule.Payment_Due_Date__c;
        }

        masterPaymentSchedule.Payment_Percent__c = totalPaymentPercent;
        masterPaymentSchedule.Name = 'On Booking';
        masterPaymentSchedule.S_No__c = 1;
        masterPaymentSchedule.Payment_Due_Date__c = dueDate;

        Map<Id, Master_Payment_Schedule__c> masterRecordsMap = new Map<Id, Master_Payment_Schedule__c>();
        for (Master_Payment_Schedule__c masterRecord : [
            SELECT Id
            FROM Master_Payment_Schedule__c
            WHERE S_No__c = 1
        ]) {
            masterRecordsMap.put(masterRecord.Id, masterRecord);
        }

        if (masterRecordsMap.containsKey(masterPaymentSchedule.Master_Payment_Schedule__c)) {
            masterPaymentSchedule.Master_Payment_Schedule__c = masterRecordsMap.get(masterPaymentSchedule.Master_Payment_Schedule__c).Id;
        }

        update masterPaymentSchedule;

        for (Payment_Schedule__c paymentSchedule : paymentSchedules) {
            if (paymentSchedule.Id != masterPaymentSchedule.Id) {
                delete paymentSchedule;
            }
        }
    }

    private static Payment_Schedule__c findMasterPaymentSchedule(List<Payment_Schedule__c> paymentSchedules) {
      
        return paymentSchedules[0];
    }
}