force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Amount_By_Bank__c.field-meta.xml
<CustomField>
    <fullName>Amount_By_Bank__c</fullName>
    <label>Amount By Bank</label>
    <summarizedField>Receipt__c.Amount_By_Bank__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt__c.Approval_status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Sanctioned_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sanctioned_Amount__c</fullName>
    <label>Loan Sanctioned Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Welcome call</fullName>
            </value>
            <value>
                <fullName>Legal Process</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Closed won</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
                <isActive>false</isActive>
                <label>Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Cost_Ex_Leg_Main__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_Ex_Leg_Main__c</fullName>
    <label>Total Cost (Ex. Leg.,Reg &amp; Main.)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Master_Payment_Schedule__c/Master_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Master Payment Schedule</label>
    <nameField>
        <label>Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/Amount_Received_From_Bank__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received_From_Bank__c</fullName>
    <label>Amount Received From Bank</label>
    <summarizedField>Receipt_Line_Item__c.Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Payment_From__c</field>
        <operation>equals</operation>
        <value>Bank</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt_Line_Item__c.Payment_schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Amount_Received_From_Customer__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received_From_Customer__c</fullName>
    <label>Amount Received From Customer</label>
    <summarizedField>Receipt_Line_Item__c.Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Payment_From__c</field>
        <operation>equals</operation>
        <value>Customer</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt_Line_Item__c.Payment_schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/AmountB__c.field-meta.xml
<CustomField>
    <fullName>AmountB__c</fullName>
    <formula>IF(Is_True_Project_Booking__c == true,Booking__r.Total_Cost_Ex_Leg_Main__c * Payment_percent__c ,
			IF(AND(S_No__c == 1, Name != &apos;Merged Schedules&apos;),
				Booking__r.Booking_Amount__c,
				IF(Booking__r.Property_TypeFor__c = &apos;Villa&apos;,
								IF(S_No__c == 2,
												IF(Master_Payment_Schedule__r.Is_Land__c = true,
																(Booking__r.Land_Cost__c * Payment_percent__c) - Booking__r.Booking_Amount__c,
																Amount__c
												),
												IF(Master_Payment_Schedule__r.Is_Land__c = true,
																Booking__r.Land_Cost__c * Payment_percent__c,
																(Booking__r.Total_Cost_Ex_Leg_Main__c - Booking__r.Land_Cost__c )* Payment_percent__c
												)
								),
								if(S_No__c == 2,  
										 (Booking__r.Total_Cost_Ex_Leg_Main__c * Payment_percent__c) - Booking__r.Booking_Amount__c,
											Booking__r.Total_Cost_Ex_Leg_Main__c * Payment_percent__c)
				)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AmountB</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Master_Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Master_Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Payment Schedule</label>
    <referenceTo>Master_Payment_Schedule__c</referenceTo>
    <relationshipLabel>Payment schedules</relationshipLabel>
    <relationshipName>Payment_schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <externalId>true</externalId>
    <label>S No</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Demanded</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Plots</fullName>
            </value>
            <value>
                <fullName>Villas &amp; Plots</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/getDRLAmountValues.cls
public class getDRLAmountValues {
    public Id bookingRecord;
    public string currentProjectStage{get;set;}
    public Decimal customerAmount{get;set;}
    public Decimal bankAmount{get;set;}
    public String bankAmountString{get;set;}
    public Decimal currentScheduleAmount{get;set;}
    public String currentScheduleAmountInString{get;set;}
    public String totalAmountstring{get;set;}
    public String SanctionedAmountstring{get;set;}
    
    
    public getDRLAmountValues(ApexPages.StandardController stdController) {
        bookingRecord = (Id)stdController.getId();
        Booking__c bk = [select id,name,project__c,property_type__c,Total_Cost_Ex_Leg_Main__c,Sanctioned_Amount__c,Amount_By_Bank__c from Booking__c where Id =:bookingRecord ];
        totalAmountstring = bk.Total_Cost_Ex_Leg_Main__c.setScale(2).format();
        if(bk.Amount_By_Bank__c != null && bk.Amount_By_Bank__c != 0){
            bankAmountString = bk.Amount_By_Bank__c.setScale(2).format();
            
        }
        if(bk.Sanctioned_Amount__c != null){
            SanctionedAmountstring = bk.Sanctioned_Amount__c.setScale(2).format();
            
        }
        Project__c proj = [select id,name from Project__c where Project__c =: bk.project__c];
        if(bk.property_type__c == 'Apartment'){
            Master_Payment_Schedule__c msp = [select id,name from Master_Payment_Schedule__c where Status__c = 'Completed' and Project__c =:proj.Id and Completed_Date__c != null order by S_No__c desc limit 1];
            List<Payment_Schedule__c> paySche = [select id,Master_Payment_Schedule__c,name,AmountB__c,Amount__c,Amount_Received_From_Bank__c,Amount_Received_From_Customer__c from Payment_Schedule__c where Booking__c =:bookingRecord];
            customerAmount = 0;
            bankAmount = 0;
            if(paySche.size()>0){
                for(Payment_Schedule__c ps : paySche){
                    if(ps.Master_Payment_Schedule__c == msp.Id){
                        currentProjectStage = ps.Name;
                        currentScheduleAmount = ps.AmountB__c;
                        currentScheduleAmountInString = currentScheduleAmount.setScale(2).format();
                    }
                    if (ps.Amount_Received_From_Customer__c != null) {
                        customerAmount += ps.Amount_Received_From_Customer__c;
                    }
                    if (ps.Amount_Received_From_Bank__c != null) {
                        bankAmount += ps.Amount_Received_From_Bank__c;
                    }
                }
                
            }
        }
        else {
            List<Payment_Schedule__c> paySche = [select id,name,Amount__c,Amount_Received_From_Bank__c,Amount_Received_From_Customer__c from Payment_Schedule__c where Booking__c =:bookingRecord and Status__c = 'Completed' and Project__c =:proj.Id and Completed_Date__c != null order by S_No__c desc limit 1];
            List<Payment_Schedule__c> payScheList = [select id,name,Amount__c,Amount_Received_From_Bank__c,Amount_Received_From_Customer__c from Payment_Schedule__c where Booking__c =:bookingRecord and Status__c = 'Completed' and Project__c =:proj.Id and Completed_Date__c != null];
            customerAmount = 0;
            bankAmount = 0;
            if(paySche.size()>0){
                currentProjectStage = paySche[0].Name;
                currentScheduleAmount = paySche[0].Amount__c;
                currentScheduleAmountInString = currentScheduleAmount.setScale(2).format();
            }
            
            for(Payment_Schedule__c ps : payScheList){
                if (ps.Amount_Received_From_Customer__c != null) {
                    customerAmount += ps.Amount_Received_From_Customer__c;
                }
                if (ps.Amount_Received_From_Bank__c != null) {
                    bankAmount += ps.Amount_Received_From_Bank__c;
                }
            }
            
        }
        
        
    }

}