force-app/main/default/objects/Additional_Charge__c/Additional_Charge__c.object-meta.xml
<CustomObject>
    <label>Additional Charge</label>
    <nameField>
        <label>Additional Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Charge__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>RTGS</fullName>
            </value>
            <value>
                <fullName>cheque</fullName>
            </value>
            <value>
                <fullName>NEFT</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>IMPS</fullName>
            </value>
            <value>
                <fullName>RTGS/IMPS/NEFT</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SBI</fullName>
            </value>
            <value>
                <fullName>Navi</fullName>
            </value>
            <value>
                <fullName>HDFC</fullName>
            </value>
            <value>
                <fullName>Tata Capital</fullName>
            </value>
            <value>
                <fullName>IIFL</fullName>
            </value>
            <value>
                <fullName>LT</fullName>
                <label>L&amp;T</label>
            </value>
            <value>
                <fullName>Union Bank</fullName>
            </value>
            <value>
                <fullName>Canara</fullName>
            </value>
            <value>
                <fullName>Shriram</fullName>
            </value>
            <value>
                <fullName>PNB</fullName>
            </value>
            <value>
                <fullName>Bajaj</fullName>
            </value>
            <value>
                <fullName>ICICI</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Piramal</fullName>
            </value>
            <value>
                <fullName>Allahabad Bank</fullName>
            </value>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Anand Rathi</fullName>
            </value>
            <value>
                <fullName>Axis</fullName>
            </value>
            <value>
                <fullName>Godrej</fullName>
            </value>
            <value>
                <fullName>BOI</fullName>
            </value>
            <value>
                <fullName>Karnataka Bank</fullName>
            </value>
            <value>
                <fullName>Central bank</fullName>
            </value>
            <value>
                <fullName>Yes Bank</fullName>
            </value>
            <value>
                <fullName>Bank Of Maharashtra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Mode_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_Of_Payment__c</fullName>
    <label>Mode Of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>HomeLoan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount__c</fullName>
    <formula>Total_received_Amount__c -  Refunded_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Received Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Consideration_with_taxes_and_other__c.field-meta.xml
<CustomField>
    <fullName>Total_Consideration_with_taxes_and_other__c</fullName>
    <formula>IF(ISNULL(Quote__c),Total_With_Taxswap__c,Quote__r.Total_Consideration_with_taxes_and_other__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Consideration with taxes and other</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_received_Amount__c</fullName>
    <label>Total Receipt Amount</label>
    <summarizedField>Receipt__c.Total_Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt__c.Approval_status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt_Line_Item__c/Receipt_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Receipt Line Item</label>
    <nameField>
        <label>Receipt Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Approval_Status1__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status1__c</fullName>
    <label>Approval Status Actual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipt Line Items</relationshipLabel>
    <relationshipName>Receipt_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>RTGS</fullName>
            </value>
            <value>
                <fullName>cheque</fullName>
            </value>
            <value>
                <fullName>NEFT</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>IMPS</fullName>
            </value>
            <value>
                <fullName>RTGS/IMPS/NEFT</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Payment_schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_schedule__c</fullName>
    <label>Payment schedule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Payment_schedule__c.Booking__c</field>
            <operation>equals</operation>
            <valueField>$Source.Booking__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payment_schedule__c</referenceTo>
    <relationshipLabel>Receipt Line Items</relationshipLabel>
    <relationshipName>Receipt_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ConsolidatedReceiptController.cls
public class ConsolidatedReceiptController {
    public Booking__c booking { get; set; }
    public String totalAmount { get; set; }
    public String receiptAmountInWords { get; set; }
    public String receiptAmountInString { get; set; }
    public List<ReceiptWrapper> repList {get;set;}
    public List<AdditionalChargesWrapper> acwBookList {get;set;}
    public class ReceiptWrapper{
        public date receiptDate{get;set;}
        public String receiptAmount{get;set;}
        public String modeOfPayment{get;set;}
        public String instruMentNo{get;set;}
        public String payNameName{get;set;}
    }
    public class AdditionalChargesWrapper{
        public date acDate{get;set;}
        public String acAmount{get;set;}
        public String acName{get;set;}
    }
    public ConsolidatedReceiptController(ApexPages.StandardController stdController) {
        // Get the current record ID from the standard controller
        Id bookingId = (Id)stdController.getId();
        
        // Query the Booking__c object with related Receipts__r
        booking = [SELECT Id, Name, Total_Consideration_with_taxes_and_other__c,Total_received_Amount__c,
                   (SELECT Id,Receipt_date__c,Bank_Name__c, Name,Cheque_no_Transaction_Number__c,Mode_of_Payment__c,Amount__c 
                    FROM Receipt_Line_Items__r where Approval_Status1__c = 'Approved' ORDER BY Name ASC),(select id,name,Amount__c from Additional_Charges__r) 
                   FROM Booking__c WHERE Id = :bookingId];
        receiptAmountInString = booking.Total_received_Amount__c.setScale(2).format(); 
        List<Receipt_Line_Item__c> repLst = [select id,name,Amount__c,Received_Amount__c,Payment_schedule__r.Name,Mode_of_Payment__c,Cheque_no_Transaction_Number__c,Bank_Name__c,Receipt_Date__c,Booking__c from Receipt_Line_Item__c where Booking__c =: bookingId and  Approval_Status1__c = 'Approved'];
        List<Additional_Charge__c> acList = [select id,name,Amount__c,Date__c from Additional_Charge__c where Booking__c =:bookingId ];
        List<ReceiptWrapper> reppList = new List<ReceiptWrapper>();
        List<AdditionalChargesWrapper> acwList = new List<AdditionalChargesWrapper>();
        for(Additional_Charge__c ac : acList){
            AdditionalChargesWrapper acw = new AdditionalChargesWrapper();
            acw.acDate = ac.Date__c;
            if(ac.Amount__c != null){
                acw.acAmount = ac.Amount__c.setScale(2).format();
            }
            acw.acName = ac.name;
            acwList.add(acw);
        }
        for(Receipt_Line_Item__c re : repLst){
            ReceiptWrapper rw = new ReceiptWrapper();
            rw.receiptDate = re.Receipt_Date__c;
            rw.receiptAmount = re.Amount__c.setScale(2).format();
            rw.modeOfPayment = re.Mode_of_Payment__c;
            rw.instruMentNo = re.Cheque_no_Transaction_Number__c;
            rw.payNameName = re.Payment_schedule__r.Name;
            reppList.add(rw);
        }
        repList = reppList;
        acwBookList = acwList;
        // Format total amount and convert to words
        totalAmount = Indian_currency_Format.Test(String.Valueof(booking.Total_received_Amount__c.setScale(0)));
        NumberTOWordConvertion nwcObj = new NumberTOWordConvertion();
        receiptAmountInWords = nwcObj.getNumberTOWordConvertion(booking.Total_received_Amount__c);
    }
}