force-app/main/default/objects/lead__c/lead__c.object-meta.xml
<CustomObject>
    <label>clead</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>cleads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Source__c/Related_Source__c.object-meta.xml
<CustomObject>
    <label>Enquiry Source</label>
    <nameField>
        <displayFormat>RS-{000}</displayFormat>
        <label>Enquiry Source</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiry Sources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Source__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Enquiry Sources</relationshipLabel>
    <relationshipName>Enquiry_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Source__c/fields/Source_OTP__c.field-meta.xml
<CustomField>
    <fullName>Source_OTP__c</fullName>
    <label>Source OTP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OTPBatchClassTestRS.cls
@isTest
public class OTPBatchClassTestRS {
    
     @isTest
    static void testBatchExecution() {
        // Create test data
        Lead testLead = new Lead(
            LastName = 'Test Lead',
            Company='Test',
            Phone__c = '1234567890',
            Allocated_Project__c = 'Test Project'
        );
        insert testLead;
        
        Related_Source__c testRelatedSource = new Related_Source__c(
            Source_OTP__c = 'TestOTP',
            Lead__c = testLead.Id
        );
        insert testRelatedSource;
        
        // Create a Set of Related_Source__c Ids
        Set<Id> leadIds = new Set<Id>{ testRelatedSource.Id };
        
        // Create an instance of the batch class
        OTPBatchClassRS batchInstance = new OTPBatchClassRS(leadIds, 200, 'TestOTPType');
        
        // Start the test
        Test.startTest();
        
        // Execute the batch class
        Database.executeBatch(batchInstance);
        
        // End the test
        Test.stopTest();
    }
    
}