force-app/main/default/objects/Follow_up__c/Follow_up__c.object-meta.xml
<CustomObject>
    <label>Follow up</label>
    <nameField>
        <displayFormat>F-{000}</displayFormat>
        <label>Follow up Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_up__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZLead</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Follow ups</relationshipLabel>
    <relationshipName>Follow_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <defaultValue>&apos;Follow Up&apos;</defaultValue>
    <label>Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/lead__c/lead__c.object-meta.xml
<CustomObject>
    <label>clead</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>cleads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/lead__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Followup Subject</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/lead__c/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round_Robin__c/Round_Robin__c.object-meta.xml
<CustomObject>
    <label>Round Robin</label>
    <nameField>
        <displayFormat>RR{00}</displayFormat>
        <label>Round Robin Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robins</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Round_Robins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Member__c/Round_Robin_Member__c.object-meta.xml
<CustomObject>
    <label>Round Robin Member</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Round Robin Members Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Member__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Sales</fullName>
                <default>true</default>
                <label>Pre Sales</label>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
                <isActive>false</isActive>
                <label>Channel Partner</label>
            </value>
            <value>
                <fullName>Post Sales</fullName>
                <isActive>false</isActive>
                <label>Post Sales</label>
            </value>
            <value>
                <fullName>Sales</fullName>
                <isActive>false</isActive>
                <label>Sales</label>
            </value>
            <value>
                <fullName>Site visit</fullName>
                <isActive>false</isActive>
                <label>Site visit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SiteVisit-{0000}</displayFormat>
        <label>Site Visits Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Scheduled Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HomeNotificationControllerTest.cls
@isTest
public class HomeNotificationControllerTest {

    public static testMethod void getInformationTest()
    {
       
        //List<Follow_Up__c> getFollowup=HomeNotificationController.getFollowUpInformation();
        //List<Site_Visit__c> getSv=HomeNotificationController.getSiteVistInformation();
        //List<Follow_Up__c> getPendingFollowup=HomeNotificationController.getPendingFollowUpInformation();
        //List<Site_Visit__c> getPendingSv=HomeNotificationController.getPendingSiteVistInformation();
        //List<Task> getTask=HomeNotificationController.getMissedCallTask();
        
        //Creating a Round Robin 
        Round_Robin__c rr=new Round_Robin__c();
        //rr.RR_Type__c='Project-Wise';
        //rr.Zone__c='Chennai';
        rr.Active__c=true;
        insert rr;
        //Creating a Round Robin Member
        Round_Robin_Member__c rm=new Round_Robin_Member__c();
        rm.User__c=userinfo.getUserId();
        rm.User_Type__c='Pre Sales';
        rm.Round_Robin__c=rr.id;
        rm.Active__c=true;
        insert rm;
        //Creating a Lead
        lead l=new lead();
        l.LastName='test user';
        l.Company='Manual Lead';
        l.Phone__c='2323344556';
        l.Allocated_Project__c='Indradhanush';
        l.Status='New';
        l.Email__c='patil@gmail.com';
        l.Lead_source__c ='Website';
        insert l;
		//Creating a Sv for Created Lead
        Site_Visit__c sv=new Site_Visit__c();  
        sv.Date__c= Datetime.now().addMinutes(1);
       	sv.Status__c='Scheduled';
        sv.Project__c='Test Project';
        //sv.Lead__c=l.id;
        insert sv;
        
        Follow_Up__c fp = new Follow_Up__c();
        fp.Scheduled_Date__c = Datetime.now().addMinutes(1);
        fp.SLead__c = l.id;
        fp.Subject__c = 'test';
        insert fp;
        
	//Updating SV Status
    String updateResult=HomeNotificationController.updateSvDetils(sv.id,'Cancelled' , 'Cancelled Commenrts',null);
    String updateResult1=HomeNotificationController.updateSvDetils(sv.id,'Completed' , 'Conducted comments','16/09/2025, 19:00:00');
    String updateResult2=HomeNotificationController.updateSvDetils(sv.id,'Rescheduled' , '16/09/2025, 18:00:00',null);
        HomeNotificationController.updateFollowupDetails(fp.Id,'Completed','dshkdkfjd');
        HomeNotificationController.todaysLeads(1,10);
        HomeNotificationController.getFollowUpInformation(1,10);
        HomeNotificationController.getSiteVistInformation(1,10);
        HomeNotificationController.todaysBookings(1,10);
        HomeNotificationController.getPendingFollowUpInformation();
        HomeNotificationController.getPendingSiteVistInformation();
        HomeNotificationController.getUserName();
        HomeNotificationController.getnoactivityleads(1,10);
        HomeNotificationController.getNoFollowUpLeads(1,10);
        
        
        
    

       
  }

    
}