force-app/main/default/objects/Follow_up__c/Follow_up__c.object-meta.xml
<CustomObject>
    <label>Follow up</label>
    <nameField>
        <displayFormat>F-{000}</displayFormat>
        <label>Follow up Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_up__c/fields/Lead1__c.field-meta.xml
<CustomField>
    <fullName>Lead1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZLead</label>
    <referenceTo>lead__c</referenceTo>
    <relationshipLabel>Follow ups</relationshipLabel>
    <relationshipName>Follow_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZLead</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Follow ups</relationshipLabel>
    <relationshipName>Follow_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/lead__c/lead__c.object-meta.xml
<CustomObject>
    <label>clead</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>cleads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/followUpController.cls
public class followUpController {
   
@AuraEnabled
    public static List<Follow_Up__c> getFollowUpDetails(String leadId)
    {
        
       List<Follow_Up__c> folloUpDetails=[Select Scheduled_Date__c,Status__c from Follow_Up__c where Lead1__c=:leadId and Status__c='Scheduled' order by createdDate Desc limit 1];
        return folloUpDetails;
    }
/*@AuraEnabled
	public static String newFollowUp(String leadId,String followupDate)
    {
         UserRecordAccess usaccess = [SELECT RecordId, HasEditAccess FROM UserRecordAccess WHERE UserId =: userinfo.getUserId() AND RecordId =: leadId];
        string returnmsg;
        if(usaccess.HasEditAccess){
        System.debug('newFolloUp');
       String formattedFollowUpDate = dateFormat(followupDate);
            if(datetime.valueOf(formattedFollowUpDate) > system.now()){
        Follow_Up__c newFollowUp=new Follow_Up__c();
       // newFollowUp.Name=formattedFollowUpDate;
        newFollowUp.Lead__c=leadID;
        newFollowUp.Scheduled_Date__c=datetime.valueOf(formattedFollowUpDate);
        newFollowUp.Status__c='Scheduled';
        //Update Lead with the recent information
        /*Lead leadObj=[Select Next_Followup_Date__c,Followup_Type__c,Followup_Status__c from lead where id=:leadId ];
        leadObj.Next_Followup_Date__c=datetime.valueOf(formattedFollowUpDate);
        leadObj.Followup_Status__c = 'Scheduled'; 
        try{
            insert newFollowUp;
             //update leadObj;
            return 'created';
        }
        catch(Exception e)
        {
            System.debug('Something went Wrong =>'+e.getMessage());
            return null;
        }
        }else{
            return 'Select future date';
        }
        }else{
            return 'No access';
        }
    }

@AuraEnabled
	public static String updateFollowUp(String leadId,string followupRecId,String followupDate,String followupStatus)    {
        UserRecordAccess usaccess = [SELECT RecordId, HasEditAccess FROM UserRecordAccess WHERE UserId =: userinfo.getUserId() AND RecordId =: leadId];
        string returnmsg;
        if(usaccess.HasEditAccess){
     	System.debug(followupDate);
        String formattedFollowUpDate = dateFormat(followupDate);
             if(datetime.valueOf(formattedFollowUpDate) > system.now()){
       	//Lead leadObj=[Select Next_Followup_Date__c,Followup_Type__c,Followup_Status__c from lead where id=:leadId ];
        Follow_Up__c folloUpDetails=[Select Scheduled_Date__c,Status__c from Follow_Up__c where Id=:followupRecId];
			//Update Lead Details Page Fileds
        	/*leadObj.Next_Followup_Date__c=datetime.valueOf(formattedFollowUpDate);   
        	leadObj.Followup_Status__c = followupStatus; 
        //Update Followup Details Fileds
        
        folloUpDetails.Scheduled_Date__c=datetime.valueOf(formattedFollowUpDate);
        folloUpDetails.Status__c=followupStatus;
        
        try{
            //update leadObj;
            update folloUpDetails;
            return 'Updated';
        }
        catch(Exception e)
        {
            System.debug('Something went Wrong =>'+e.getMessage());
            return null;
        }
             }else{
                  return 'Select future date';
             }
        }else{
             return 'No access';
        }
    }
    */
    public static String dateFormat(String followupdate)
    { 	String dateTimeFormatted='';	
     	String formattedDate='';
     	//Split complete Date Time
        String[] splitDateTime=followupdate.split(',');
     	//Split Date 
        	String[] splitDate=splitDateTime[0].split('/');
     			for(integer i=splitDate.size()-1;i>=0;i--)
                {
                    formattedDate+=splitDate[i];
                    if(i!=0)
                        formattedDate+='-';
                }
     
     dateTimeFormatted=	formattedDate+' '+splitDateTime[1];
        
        return dateTimeFormatted;
    }
}