force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/Amount1__c.field-meta.xml
<CustomField>
    <fullName>Amount1__c</fullName>
    <formula>IF(Is_True_Project__c == true,Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c * Payment_percent__c ,IF(
					S_No__c == 1,
					Quote__r.Booking_AmountNew__c,
					IF(
									Quote__r.Property_Type_For__c = &apos;Villa&apos;,
									IF(
													S_No__c == 2,
													IF(
																	Master_Payment_Schedule__r.Is_Land__c = true,
																	((Quote__r.Land_Cost__c * Payment_percent__c)) - Quote__r.Booking_AmountNew__c,
																	Amount__c
													),
													IF(
																	Master_Payment_Schedule__r.Is_Land__c = true,
																	Quote__r.Land_Cost__c * Payment_percent__c,
																	(Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c - Quote__r.Land_Cost__c) * Payment_percent__c

													)
									),
									if(S_No__c == 2, ((Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c * Payment_percent__c ) - Quote__r.Booking_AmountNew__c),Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c * Payment_percent__c)
					)
	))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NUAmount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/AmountB__c.field-meta.xml
<CustomField>
    <fullName>AmountB__c</fullName>
    <formula>IF(Is_True_Project_Booking__c == true,Booking__r.Total_Cost_Ex_Leg_Main__c * Payment_percent__c ,
			IF(AND(S_No__c == 1, Name != &apos;Merged Schedules&apos;),
				Booking__r.Booking_Amount__c,
				IF(Booking__r.Property_TypeFor__c = &apos;Villa&apos;,
								IF(S_No__c == 2,
												IF(Master_Payment_Schedule__r.Is_Land__c = true,
																(Booking__r.Land_Cost__c * Payment_percent__c) - Booking__r.Booking_Amount__c,
																Amount__c
												),
												IF(Master_Payment_Schedule__r.Is_Land__c = true,
																Booking__r.Land_Cost__c * Payment_percent__c,
																(Booking__r.Total_Cost_Ex_Leg_Main__c - Booking__r.Land_Cost__c )* Payment_percent__c
												)
								),
								if(S_No__c == 2,  
										 (Booking__r.Total_Cost_Ex_Leg_Main__c * Payment_percent__c) - Booking__r.Booking_Amount__c,
											Booking__r.Total_Cost_Ex_Leg_Main__c * Payment_percent__c)
				)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AmountB</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Is_Construction__c.field-meta.xml
<CustomField>
    <fullName>Is_Construction__c</fullName>
    <formula>Master_Payment_Schedule__r.Is_Construction__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Construction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Is_Land__c.field-meta.xml
<CustomField>
    <fullName>Is_Land__c</fullName>
    <formula>Master_Payment_Schedule__r.Is_Land__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Land</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/NUAmountRain__c.field-meta.xml
<CustomField>
    <fullName>NUAmountRain__c</fullName>
    <formula>IF(Project_Name__c == &apos;Rhythm of Rain&apos;,Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c * Payment_percent__c ,IF(
S_No__c == 1,
Quote__r.Booking_AmountNew__c,
IF(
Quote__r.Property_Type_For__c = &apos;Villa&apos;,
IF(
S_No__c == 2,
IF(
Master_Payment_Schedule__r.Is_Land__c = true,
((Quote__r.Land_Cost__c * Payment_percent__c)) - Quote__r.Booking_AmountNew__c,
Amount__c
),
IF(
Master_Payment_Schedule__r.Is_Land__c = true,
Quote__r.Land_Cost__c * Payment_percent__c,
(Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c - Quote__r.Land_Cost__c) * Payment_percent__c

)
),
if(S_No__c == 2, ((Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c * Payment_percent__c ) - Quote__r.Booking_AmountNew__c),Quote__r.Total_Cost_After_Discount_Ex_Leg_Main__c * Payment_percent__c)
)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NUAmountRain</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <formula>IF(Quote__c != null,TEXT(Quote__r.Project__c),IF(Booking__c !=null,TEXT(Booking__r.Project__c),&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <externalId>true</externalId>
    <label>S No</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Generator_STP__c.field-meta.xml
<CustomField>
    <fullName>Generator_STP__c</fullName>
    <label>Generator/STP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Terms_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_Conditions__c</fullName>
    <label>Terms &amp; Conditions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Basic_Cost1__c.field-meta.xml
<CustomField>
    <fullName>Basic_Cost1__c</fullName>
    <label>Basic Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Construction_Cost__c.field-meta.xml
<CustomField>
    <fullName>Construction_Cost__c</fullName>
    <label>Construction Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/GST_5__c.field-meta.xml
<CustomField>
    <fullName>GST_5__c</fullName>
    <formula>Total_Basic_Cost1__c  * GST1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_Construction_Cost_With_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Construction_Cost_With_Tax__c</fullName>
    <formula>Construction_Cost__c + GST_5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Construction Cost With Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_Cost_After_Discount_Ex_Leg_Main__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_After_Discount_Ex_Leg_Main__c</fullName>
    <formula>/*IF(Property_Type_For__c = &apos;Villa&apos;,Total_Basic_Cost__c+ (Total_Basic_Cost__c * GST1__c) ,Total_Basic_Cost__c +  (Total_Basic_Cost__c * GST1__c) +  (Total_Basic_Cost__c * 0.7)/100)
Total_Basic_Cost__c +*/ GST_5__c + Lab_Cess__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost After Discount(Ex. Leg/Main))</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Water_Electricity_Charges__c.field-meta.xml
<CustomField>
    <fullName>Water_Electricity_Charges__c</fullName>
    <label>Water &amp; Electricity Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Terms_Conditions__c/Terms_Conditions__c.object-meta.xml
<CustomObject>
    <label>Terms &amp; Conditions</label>
    <nameField>
        <displayFormat>TER-{0000}</displayFormat>
        <label>Terms &amp; Conditions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms &amp; Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Terms_Conditions__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Terms &amp; Conditions</relationshipLabel>
    <relationshipName>Terms_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Terms_Conditions__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <label>S No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/getTermsAndCondition.cls
public class getTermsAndCondition {
    
    public string landCost{get;set;}
    public string constructionCost{get;set;}
    public string waterCost{get;set;}
    public string ammentiiesCost{get;set;}
    public string generatorCost{get;set;}
    public string gstCost{get;set;}
    public string totalConstuctionWithCost{get;set;}
    public string totalVilla{get;set;}
    public string basicCost{get;set;}
    
    public List<paySchWrapper> payList {get;set;}
    
    public class paySchWrapper{
        public string Name{get;set;}
        public Decimal Payment_percent{get;set;}
        public boolean isConstruction{get;set;}
        public boolean isSale{get;set;}
        public string amount{get;set;}
        public Decimal S_No{get;set;}
    }
    
    public List<Terms_Conditions__c> termsAndConditions{get;set;}
    
    public getTermsAndCondition(ApexPages.StandardController stdController) {
        Id quoteId = (Id)stdController.getId();
        Quote__c qt = [select id,name,Project__c,Land_Cost__c,Construction_Cost__c,Water_Electricity_Charges__c,Club_Amenities_Charges__c,Generator_STP__c,GST_5__c,Total_Construction_Cost_With_Tax__c,Total_Cost_After_Discount_Ex_Leg_Main__c,Basic_Cost1__c from Quote__c where Id = : quoteId];
        
        List<paySchWrapper> samp = new List<paySchWrapper>();
        List<Payment_Schedule__c> payListStan = [select id,name,NUAmountRain__c,S_No__c,Payment_Percent__c,AmountB__c,Amount1__c,Amount__c,Is_Land__c, Is_Construction__c,Project_Name__c from Payment_Schedule__c where Quote__c =:qt.id ];
        for(Payment_Schedule__c ps : payListStan){
            paySchWrapper pw = new paySchWrapper();
            pw.Name = ps.Name;
            pw.Payment_percent = ps.Payment_Percent__c;
            pw.isConstruction = ps.Is_Construction__c;
            pw.isSale = ps.Is_Land__c;
            if(ps.Project_Name__c == 'Rhythm of Rain'){
                pw.amount = ps.NUAmountRain__c.setScale(2).format();
            }
            else{
                pw.amount = ps.Amount1__c.setScale(2).format();
            }
            pw.S_No = ps.S_No__c;
            samp.add(pw);
        }
        
		payList =  samp;    
        
        if(qt.Land_Cost__c != null && qt.Land_Cost__c != 0){
            landCost = qt.Land_Cost__c.setScale(2).format();
        }
        if(qt.Basic_Cost1__c != null && qt.Basic_Cost1__c != 0){
            basicCost = qt.Basic_Cost1__c.setScale(2).format();
        }
        if(qt.Construction_Cost__c != null && qt.Construction_Cost__c != 0){
            constructionCost = qt.Construction_Cost__c.setScale(2).format();
        }
        if(qt.Water_Electricity_Charges__c != null && qt.Water_Electricity_Charges__c != 0){
            waterCost = qt.Water_Electricity_Charges__c.setScale(2).format();
        }
        if(qt.Club_Amenities_Charges__c != null && qt.Club_Amenities_Charges__c != 0){
            ammentiiesCost = qt.Club_Amenities_Charges__c.setScale(2).format();
        }
        if(qt.Generator_STP__c != null && qt.Generator_STP__c != 0){
            generatorCost = qt.Generator_STP__c.setScale(2).format();
        }
        if(qt.GST_5__c != null && qt.GST_5__c != 0){
            gstCost = qt.GST_5__c.setScale(2).format();
        }
        if(qt.Total_Construction_Cost_With_Tax__c != null && qt.Total_Construction_Cost_With_Tax__c != 0){
            totalConstuctionWithCost = qt.Total_Construction_Cost_With_Tax__c.setScale(2).format();
        }
        if(qt.Total_Cost_After_Discount_Ex_Leg_Main__c != null && qt.Total_Cost_After_Discount_Ex_Leg_Main__c != 0){
            totalVilla = qt.Total_Cost_After_Discount_Ex_Leg_Main__c.setScale(2).format();
        }
        Project__c pro = [select id,name,Terms_Conditions__c from Project__c where Project__c = :qt.Project__c ];
        termsAndConditions = [Select id,Terms__c,S_No__c from Terms_Conditions__c where Project__c =: pro.Id  order by S_No__c asc];
    }
}