force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Block</label>
    <nameField>
        <label>Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Block__c/fields/Discount_Rate_per_sqft__c.field-meta.xml
<CustomField>
    <fullName>Discount_Rate_per_sqft__c</fullName>
    <label>Discount (Rate per sqft)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Block</label>
    <referenceTo>Block__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/CP_Discount__c.field-meta.xml
<CustomField>
    <fullName>CP_Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CP Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>As on stage</fullName>
                <isActive>false</isActive>
                <label>As on stage</label>
            </value>
            <value>
                <fullName>Custom</fullName>
                <isActive>false</isActive>
                <label>Custom</label>
            </value>
            <value>
                <fullName>Differed</fullName>
                <isActive>false</isActive>
                <label>Differed</label>
            </value>
            <value>
                <fullName>Full Payment</fullName>
                <isActive>false</isActive>
                <label>Full Payment</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_status__c.field-meta.xml
<CustomField>
    <fullName>Quote_status__c</fullName>
    <label>Quote status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drafted</fullName>
                <default>true</default>
                <label>Drafted</label>
            </value>
            <value>
                <fullName>submitted for approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>sent to customer</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Rate_per_sqft_Temp__c.field-meta.xml
<CustomField>
    <fullName>Rate_per_sqft_Temp__c</fullName>
    <label>Rate per sqft</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7200</fullName>
            </value>
            <value>
                <fullName>7499</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteTriggerTest.cls
@istest
public class QuoteTriggerTest {
    @istest
    public static void method(){
        
        Lead ld231 = new Lead();
        ld231.LastName='Test lead';
        ld231.CP_Id__c = 'Ranjeevi123';
        ld231.Allocated_Project__c='Euphoria In The East';
        ld231.Phone__c='6662536253';
        ld231.Secondary_Phone__c='3312223334';
        ld231.Status = 'New';
        ld231.Lead_Assigned__c=false;
        ld231.Re_assigned_date__c = system.now();
        ld231.Lead_StatusSecondary__c = 'New';
        ld231.Lead_source__c ='Website'; 
        insert ld231;
        
        Block__c bk = new Block__c();
        bk.Discount_Rate_per_sqft__c = 100;
        bk.Name = 'test';
        insert bk;
        Quote__c qt = new Quote__c();
        qt.SLead__c = ld231.Id;
        qt.Block__c = bk.id;
        qt.Project__c = 'Euphoria In The East';
        qt.Quote_status__c='Drafted';
        qt.Discount__c=50;
        qt.CP_Discount__c = 50;
        qt.Payment_Type__c='Standard';
        insert qt;
        
        
        
        
        qt.Rate_per_sqft_Temp__c = '7200';
        update qt;
        delete qt;
        
        
        Quote__c qt1 = new Quote__c();
        qt1.SLead__c = ld231.Id;
        qt1.Block__c = bk.id;
        qt1.Project__c = 'Euphoria In The East';
        qt1.Quote_status__c='Drafted';
        qt1.Discount__c=150;
        qt1.Payment_Type__c='Standard';
        insert qt1;
    }
}