force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Block</label>
    <nameField>
        <label>Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Terms_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_Conditions__c</fullName>
    <label>Terms &amp; Conditions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Basic_Cost1__c.field-meta.xml
<CustomField>
    <fullName>Basic_Cost1__c</fullName>
    <label>Basic Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Block</label>
    <referenceTo>Block__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Construction_Cost__c.field-meta.xml
<CustomField>
    <fullName>Construction_Cost__c</fullName>
    <label>Construction Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>As on stage</fullName>
                <isActive>false</isActive>
                <label>As on stage</label>
            </value>
            <value>
                <fullName>Custom</fullName>
                <isActive>false</isActive>
                <label>Custom</label>
            </value>
            <value>
                <fullName>Differed</fullName>
                <isActive>false</isActive>
                <label>Differed</label>
            </value>
            <value>
                <fullName>Full Payment</fullName>
                <isActive>false</isActive>
                <label>Full Payment</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_status__c.field-meta.xml
<CustomField>
    <fullName>Quote_status__c</fullName>
    <label>Quote status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drafted</fullName>
                <default>true</default>
                <label>Drafted</label>
            </value>
            <value>
                <fullName>submitted for approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>sent to customer</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_Cost_Ex_Leg_Main__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_Ex_Leg_Main__c</fullName>
    <label>Total Cost (Ex. Leg. &amp; Main.)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Water_Electricity_Charges__c.field-meta.xml
<CustomField>
    <fullName>Water_Electricity_Charges__c</fullName>
    <label>Water &amp; Electricity Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schemes_Offers_Master__c/Schemes_Offers_Master__c.object-meta.xml
<CustomObject>
    <label>Schemes &amp; Offers Master</label>
    <nameField>
        <label>Schemes &amp; Offers Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes &amp; Offers Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Terms_Conditions__c/Terms_Conditions__c.object-meta.xml
<CustomObject>
    <label>Terms &amp; Conditions</label>
    <nameField>
        <displayFormat>TER-{0000}</displayFormat>
        <label>Terms &amp; Conditions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms &amp; Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Terms_Conditions__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Terms &amp; Conditions</relationshipLabel>
    <relationshipName>Terms_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/getTermsAndConditionTest.cls
@isTest
public class getTermsAndConditionTest {
    
    public static testmethod void raisedemand(){
         Lead ld = new Lead();
        ld.LastName = 'Test';
        ld.Company = 'testcompany';
        ld.Phone__c = '1111111110';
        ld.Allocated_Project__c = 'Test Project';
        ld.Lead_source__c = 'Website';
        insert ld;
        
        
        
        
        Project__c pjt = new Project__c();
        pjt.Name = 'Test Project';
        pjt.Project__c = 'Test Project';
        pjt.Active__c = true;
        pjt.Terms_Conditions__c = 'Tes';
        insert pjt;
        
        Block__c bk = new Block__c();
        bk.Name = '112344';
        bk.Project__c = pjt.Id;
        insert bk;
        Schemes_Offers_Master__c scm = new Schemes_Offers_Master__c();
        scm.Name = 'Jyst';
        insert scm;
        Quote__c qc = new Quote__c();
        qc.Quote_status__c = 'Approved';
        qc.Block__c = bk.id;
        qc.Project__c = 'Test Project';
        qc.Payment_Type__c = 'Standard';
        qc.Water_Electricity_Charges__c = 11111;
        qc.Club_Amenities_Charges__c = 54444;
        qc.Land_Cost__c = 65434567;
        qc.Construction_Cost__c = 7654356;
        qc.Basic_Cost1__c = 76543567;
        qc.Total_Cost_Ex_Leg_Main__c = 654345676;
        insert qc;
        
        Payment_Schedule__c paySch = new Payment_Schedule__c();
        paySch.Quote__c = qc.Id;
        paySch.Amount__c = 345678;
        insert paySch;
        test.starttest();
        ApexPages.StandardController sc = new  ApexPages.StandardController(qc);     
        getTermsAndCondition ext = new getTermsAndCondition(sc);
              
        test.stoptest();
    }

}