force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Block</label>
    <nameField>
        <label>Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookings5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot__c/Plot__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <label>Block Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>A6</fullName>
            </value>
            <value>
                <fullName>A7</fullName>
            </value>
            <value>
                <fullName>A8</fullName>
            </value>
            <value>
                <fullName>A9</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>B3</fullName>
            </value>
            <value>
                <fullName>B5</fullName>
            </value>
            <value>
                <fullName>B6</fullName>
            </value>
            <value>
                <fullName>B7</fullName>
            </value>
            <value>
                <fullName>B8</fullName>
            </value>
            <value>
                <fullName>B9</fullName>
            </value>
            <value>
                <fullName>B10</fullName>
            </value>
            <value>
                <fullName>B11</fullName>
            </value>
            <value>
                <fullName>B13</fullName>
            </value>
            <value>
                <fullName>B17</fullName>
            </value>
            <value>
                <fullName>B18</fullName>
            </value>
            <value>
                <fullName>B19</fullName>
            </value>
            <value>
                <fullName>B20</fullName>
            </value>
            <value>
                <fullName>B21</fullName>
            </value>
            <value>
                <fullName>B23</fullName>
            </value>
            <value>
                <fullName>B27</fullName>
            </value>
            <value>
                <fullName>B28</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C8</fullName>
            </value>
            <value>
                <fullName>C9</fullName>
            </value>
            <value>
                <fullName>C10</fullName>
            </value>
            <value>
                <fullName>C12</fullName>
            </value>
            <value>
                <fullName>C13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Plots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProjectsiFmw</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_MobileAppAPIControllerAllBookings.cls
@isTest
private class Test_MobileAppAPIControllerAllBookings {
    
    // Helper method to create test data with Projects and Towers
    private static void setupTestData() {
        // Create a Project
        Project__c testProject = new Project__c(
            Name = 'Test Project'
        );
        insert testProject;
        
        // Create a Tower (or Phase) related to the Project
        Block__c testTower = new Block__c(
            Name = 'Tower A',
            Project__c = testProject.Id
        );
        insert testTower;
        
        // Create a Plot related to the Tower and Project
        Plot__c testPlot = new Plot__c(
            Name = 'Plot 101',
            Project__c = testProject.Id
        );
        insert testPlot;
        
        // Create Bookings with the same PAN
        List<Booking__c> bookings = new List<Booking__c>();
        
        // Booking 1
        bookings.add(new Booking__c(
            PAN_Number__c = 'ABCDE1234F',
            Project__c = 'Test Project',
            Plot__c = testPlot.Id,
            Sales_Manager__c = UserInfo.getUserId()
        ));
        
        // Booking 2
        bookings.add(new Booking__c(
            PAN_Number__c = 'ABCDE1234F', // Same PAN
            Project__c = 'Test Project',
            Plot__c = testPlot.Id,
            Sales_Manager__c = UserInfo.getUserId()
        ));
        
        insert bookings;
    }
    
    // Test the successful case: PAN exists with multiple bookings
    @isTest
    static void testAllBookings_Success() {
        // Setup test data
        setupTestData();
        
        // Set up the REST request
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        // Create the input wrapper JSON
        MobileAppAPIControllerAllBookings.InputWrapper input = new MobileAppAPIControllerAllBookings.InputWrapper();
        input.pan_number = 'ABCDE1234F'; // PAN from test data
        input.booking_id = '';
        
        String requestBody = JSON.serialize(input);
        
        // Set up the request
        req.requestURI = '/services/apexrest/all_bookings/all_bookings'; // The URL Mapping
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(requestBody);
        
        RestContext.request = req;
        RestContext.response = res;
        
        // Execute the test
        Test.startTest();
        MobileAppAPIControllerAllBookings.AllBookingsResponse response = MobileAppAPIControllerAllBookings.mobileappmethod();
        Test.stopTest();

     
        
     
    }
    
    // Test the case where PAN does not exist (should return 404)
    @isTest
    static void testAllBookings_NotFound() {
        // No test data setup -> no bookings with this PAN
        
        // Set up the REST request
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        MobileAppAPIControllerAllBookings.InputWrapper input = new MobileAppAPIControllerAllBookings.InputWrapper();
        input.pan_number = 'NONEXISTENT'; // PAN that doesn't exist
        input.booking_id = '';
        
        String requestBody = JSON.serialize(input);
        
        req.requestURI = '/services/apexrest/all_bookings/all_bookings';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(requestBody);
        
        RestContext.request = req;
        RestContext.response = res;
        
        // Execute the test
        Test.startTest();
        MobileAppAPIControllerAllBookings.AllBookingsResponse response = MobileAppAPIControllerAllBookings.mobileappmethod();
        Test.stopTest();
        
    
    }
    
    // Test the case where PAN number is blank (should return 400 Bad Request)
    @isTest
    static void testAllBookings_BlankPAN() {
        // Set up the REST request
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        MobileAppAPIControllerAllBookings.InputWrapper input = new MobileAppAPIControllerAllBookings.InputWrapper();
        input.pan_number = ''; // Blank PAN - this should trigger the error
        input.booking_id = '';
        
        String requestBody = JSON.serialize(input);
        
        req.requestURI = '/services/apexrest/all_bookings/all_bookings';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(requestBody);
        
        RestContext.request = req;
        RestContext.response = res;
        
        // Execute the test
        Test.startTest();
        MobileAppAPIControllerAllBookings.AllBookingsResponse response = MobileAppAPIControllerAllBookings.mobileappmethod();
        Test.stopTest();
        

    }
    
    // Test the case where URL path doesn't match 'all_bookings'
    @isTest
    static void testAllBookings_InvalidEndpoint() {
        // Setup test data
        setupTestData();
        
        // Set up the REST request with different endpoint
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        MobileAppAPIControllerAllBookings.InputWrapper input = new MobileAppAPIControllerAllBookings.InputWrapper();
        input.pan_number = 'ABCDE1234F';
        input.booking_id = '';
        
        String requestBody = JSON.serialize(input);
        
        // Use a different endpoint that doesn't match 'all_bookings'
        req.requestURI = '/services/apexrest/all_bookings/some_other_endpoint';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(requestBody);
        
        RestContext.request = req;
        RestContext.response = res;
        
        // Execute the test
        Test.startTest();
        MobileAppAPIControllerAllBookings.AllBookingsResponse response = MobileAppAPIControllerAllBookings.mobileappmethod();
        Test.stopTest();
      
    }
    
    // Test exception handling
    @isTest
    static void testAllBookings_Exception() {
        // Force an exception by using malformed JSON
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        // Send invalid JSON that can't be deserialized
        String invalidJson = '{ "pan_number": "TEST1234"'; // Missing closing brace
        
        req.requestURI = '/services/apexrest/all_bookings/all_bookings';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(invalidJson);
        
        RestContext.request = req;
        RestContext.response = res;
        
        // Execute the test
        Test.startTest();
        MobileAppAPIControllerAllBookings.AllBookingsResponse response = MobileAppAPIControllerAllBookings.mobileappmethod();
        Test.stopTest();
        

    }
    
    // Test with bookings that have null Plot relationships
    @isTest
    static void testAllBookings_NullRelationships() {
        // Create a Booking without Plot relationship
        Booking__c testBooking = new Booking__c(
            PAN_Number__c = 'TESTPAN123',
            Project__c = 'Test Project',
            Sales_Manager__c = UserInfo.getUserId()
            // Plot__c is null - this will test the relationship handling
        );
        insert testBooking;
        
        // Set up the REST request
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        MobileAppAPIControllerAllBookings.InputWrapper input = new MobileAppAPIControllerAllBookings.InputWrapper();
        input.pan_number = 'TESTPAN123';
        input.booking_id = '';
        
        String requestBody = JSON.serialize(input);
        
        req.requestURI = '/services/apexrest/all_bookings/all_bookings';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(requestBody);
        
        RestContext.request = req;
        RestContext.response = res;
        
        // Execute the test
        Test.startTest();
        MobileAppAPIControllerAllBookings.AllBookingsResponse response = MobileAppAPIControllerAllBookings.mobileappmethod();
        Test.stopTest();
        
      
    }
}